// Country/region data for Europe.
// Alphabetically ordered by name. Each entry:
//   id   - unique unit id (matches the map's country iso3 code, or iso3_region for
//          countries split into multiple climate regions)
//   iso  - ISO 3166-1 alpha-3 code used to match the map's GeoJSON country outlines
//   name - display name shown in the table and on the map
//   lat/lng - marker position on the map
//   climate - { codes, extra, note } or null if not yet researched
//     codes: 12-character string (JAN..DEC), one of V(avoid) / O(ok) / I(ideal)
//     extra: 12-entry array, each entry a combination of icon codes for that month
//            (or ""): H = extreme heat, C = extreme cold, R = extreme rain/monsoon,
//            T = overrun with tourists (only used where this is a genuine concern)
//     note: short free-text shown in a popup when clicking the country name
//   complexity - object with 9 fields (visa, particular, stayLength, extendStay,
//     carnet, vehicleStay, extendVeh, modernVeh, roadQuality), or null if not yet
//     researched. Each field: { level: "easy"|"moderate"|"hard", label, detail }
//   See /llm_update_instructions.md for the research prompt used to fill these in.
(function() {
  const EUROPE_COUNTRIES = [
    { id: "ALB", iso: "ALB", name: "Albania", lat: 41.16, lng: 20.16, continent: "Europe",
      climate: {
        codes: "OOOIIIVVIIIO",
        extra: ["", "", "", "", "", "HT", "H", "H", "T", "", "", ""],
        note: "Best May-June and September-October; hot and crowded coastline July-August.",
      },
      complexity: {
        visa: { level: "easy", label: "Visa-free, non-Schengen", detail: "EU/Belgian citizens enter visa-free for up to 90 days in a 180-day period. Not in Schengen, so a separate passport stamp applies but the process at the border is quick." },
        particular: { level: "easy", label: "No special permits", detail: "No mandatory guide or region permits for standard tourist travel; foreign-plated vehicles circulate freely." },
        stayLength: { level: "easy", label: "90 days", detail: "Standard tourist stay is 90 days within a 180-day rolling window." },
        extendStay: { level: "moderate", label: "Possible via immigration office", detail: "Extensions beyond 90 days require an application at local immigration police; not routine for short-term tourists, easier to simply exit/re-enter via Montenegro/Greece/Kosovo." },
        carnet: { level: "easy", label: "Not required", detail: "No Carnet de Passage needed; a temporary import is stamped in the passport/vehicle registration at the border, free of charge." },
        vehicleStay: { level: "easy", label: "Matches 90-day stay", detail: "Vehicle temporary import is tied to the traveler's 90-day allowance." },
        extendVeh: { level: "moderate", label: "Tied to visa extension", detail: "Extending the vehicle's stay requires the same immigration process as a personal stay extension." },
        modernVeh: { level: "easy", label: "Good fuel, growing service", detail: "Diesel quality is fine and widely available; Mercedes dealer presence exists in Tirana, though Sprinter-specific parts may need ordering from Italy/Greece." },
        roadQuality: { level: "moderate", label: "Improving but mountainous", detail: "Main coastal and Tirana-area roads are good; mountain roads in the north/northeast are narrow, winding, and can be affected by landslides after heavy rain." },
      },
    },
    { id: "AUT", iso: "AUT", name: "Austria", lat: 47.74, lng: 13.23, continent: "Europe",
      climate: {
        codes: "VVOIIOOOIIOV",
        extra: ["C", "C", "", "", "", "", "H", "HT", "", "", "", "C"],
        note: "Best May-June and September; alpine winters bring heavy snow, summer can be busy in tourist towns.",
      },
      complexity: {
        visa: { level: "easy", label: "EU/Schengen, no formality", detail: "Belgium and Austria are both EU/Schengen members; no visa, no border checks, full freedom of movement." },
        particular: { level: "easy", label: "Vignette for motorways", detail: "A digital or sticker highway vignette is mandatory for motorway use; low-emission zones apply in some city centers (Sprinter Euro6 qualifies easily)." },
        stayLength: { level: "easy", label: "Unlimited (EU citizen)", detail: "As an EU citizen you may stay indefinitely without registration formalities for typical travel durations." },
        extendStay: { level: "easy", label: "Not applicable", detail: "No stay limit to extend as an EU/Schengen national." },
        carnet: { level: "easy", label: "Not required", detail: "No carnet or customs paperwork needed for an EU-registered vehicle moving within the EU/Schengen area." },
        vehicleStay: { level: "easy", label: "Unrestricted", detail: "No temporary import restrictions for an EU-plated vehicle." },
        extendVeh: { level: "easy", label: "Not applicable", detail: "No vehicle stay limit exists to extend." },
        modernVeh: { level: "easy", label: "Excellent, full dealer network", detail: "Ultra-low-sulphur diesel and AdBlue are universally available; extensive Mercedes-Benz dealer/service network throughout the country." },
        roadQuality: { level: "easy", label: "Excellent, alpine passes seasonal", detail: "Roads are excellent and well-maintained; some high alpine passes close in winter due to snow, well-signposted with alternatives." },
      },
    },
    { id: "BLR", iso: "BLR", name: "Belarus", lat: 53.74, lng: 27.95, continent: "Europe",
      climate: {
        codes: "VVOOIIOOIOOV",
        extra: ["C", "C", "", "", "", "", "H", "", "", "", "", "C"],
        note: "Best May-June and September; cold, dark winters with icy roads Nov-March.",
      },
      complexity: {
        visa: { level: "hard", label: "e-Visa limited, EU tensions", detail: "Belarus offers a 30-day visa-free regime for some nationalities via Minsk airport only, not land borders; for overland EU travelers a visa is normally required and EU-Belarus relations/sanctions since 2021 make this unpredictable. Check current status closely before planning, as it changes frequently." },
        particular: { level: "hard", label: "Registration, restricted zones", detail: "Foreigners staying beyond a few days must register with local authorities; border areas and some zones require caution. Political situation makes independent travel advice from your embassy essential." },
        stayLength: { level: "moderate", label: "Visa-dependent, typically 30 days", detail: "Standard tourist visas allow up to 30 days; visa-free entry (where applicable) is more restrictive." },
        extendStay: { level: "hard", label: "Not straightforward", detail: "Extensions require dealing with Belarusian immigration bureaucracy; not recommended given current diplomatic climate." },
        carnet: { level: "moderate", label: "Temporary import at border", detail: "No land border crossing exists from EU/Schengen directly (Belarus borders Poland, Lithuania, Latvia which are EU); a Carnet de Passage is not usually demanded but customs declaration for the vehicle is required at entry." },
        vehicleStay: { level: "moderate", label: "Tied to visa validity", detail: "Vehicle temporary import period matches the traveler's visa duration." },
        extendVeh: { level: "hard", label: "Difficult, avoid if possible", detail: "Extending vehicle permits mirrors the difficulty of extending a personal visa." },
        modernVeh: { level: "moderate", label: "Adequate fuel, no Mercedes-Benz dealer support post-2022", detail: "Diesel is available and reasonably priced, but Mercedes-Benz suspended official dealer/parts support following sanctions; carry spares and expect no factory servicing." },
        roadQuality: { level: "moderate", label: "Decent main roads", detail: "Major highways (e.g. Minsk-Brest) are in reasonable condition; rural roads can be rough, and winter driving requires caution for ice/snow." },
      },
    },
    { id: "BEL", iso: "BEL", name: "Belgium", lat: 50.5, lng: 4.34, continent: "Europe",
      climate: {
        codes: "OOOOIIIIIOOO",
        extra: ["", "", "", "", "", "", "", "", "", "", "", ""],
        note: "Mild year-round; best May-September, with July-August busiest and occasionally hot.",
      },
      complexity: {
        visa: { level: "easy", label: "Home country", detail: "Home country for this traveler; no formalities." },
        particular: { level: "easy", label: "Low-emission zones", detail: "LEZ zones exist in Brussels, Antwerp and Ghent; a modern Euro6 Sprinter qualifies without issue, but registration/sticker may be required in some cities." },
        stayLength: { level: "easy", label: "Unlimited", detail: "No stay limit for a Belgian resident/citizen." },
        extendStay: { level: "easy", label: "Not applicable", detail: "No stay limit to extend." },
        carnet: { level: "easy", label: "Not required", detail: "Vehicle is domestically registered; no import paperwork needed." },
        vehicleStay: { level: "easy", label: "Unrestricted", detail: "Home-registered vehicle, no temporary import limits." },
        extendVeh: { level: "easy", label: "Not applicable", detail: "No vehicle stay limit exists." },
        modernVeh: { level: "easy", label: "Full dealer network", detail: "Complete Mercedes-Benz dealer and parts network; base country for this vehicle." },
        roadQuality: { level: "easy", label: "Excellent", detail: "Dense, well-maintained road network; occasional traffic congestion around major cities." },
      },
    },
    { id: "BIH", iso: "BIH", name: "Bosnia and Herzegovina", lat: 43.94, lng: 17.67, continent: "Europe",
      climate: {
        codes: "OOOIIIVVIIIO",
        extra: ["", "", "", "", "", "H", "H", "H", "", "", "", ""],
        note: "Best May-June and September; hot, dry summers, cold winters especially in mountain areas.",
      },
      complexity: {
        visa: { level: "easy", label: "Visa-free, non-Schengen", detail: "EU/Belgian citizens enter visa-free for up to 90 days in any 180-day period; separate passport stamps apply as it's outside Schengen." },
        particular: { level: "easy", label: "No special permits", detail: "No mandatory guide or region-specific permits for standard tourist/overland travel; be aware of marked minefield remnants from the 1990s war in rural/forest areas away from roads." },
        stayLength: { level: "easy", label: "90 days", detail: "Standard tourist stay allowance is 90 days within 180 days." },
        extendStay: { level: "moderate", label: "Possible via local police", detail: "Extensions require application at a local police administration office; not routine, easier to exit and re-enter via a neighboring country." },
        carnet: { level: "easy", label: "Not required", detail: "No Carnet de Passage needed; a simple temporary import stamp is given at the border free of charge." },
        vehicleStay: { level: "easy", label: "Matches 90-day stay", detail: "Vehicle import period is tied to the traveler's 90-day tourist allowance." },
        extendVeh: { level: "moderate", label: "Tied to visa extension", detail: "Extending vehicle stay requires the same process as a personal visa extension." },
        modernVeh: { level: "moderate", label: "Fuel fine, limited dealer support", detail: "Diesel quality and availability are adequate; no official Mercedes-Benz dealer in-country, nearest full service typically in Croatia." },
        roadQuality: { level: "moderate", label: "Mountainous, mixed quality", detail: "Main routes (e.g. Sarajevo-Mostar) are decent; many mountain and rural roads are narrow, winding, with limited winter maintenance." },
      },
    },
    { id: "BGR", iso: "BGR", name: "Bulgaria", lat: 42.73, lng: 25.47, continent: "Europe",
      climate: {
        codes: "OOOIIOVVIIOO",
        extra: ["", "", "", "", "", "", "H", "H", "", "", "", ""],
        note: "Best April-June and September; hot summers with crowded Black Sea coast in August.",
      },
      complexity: {
        visa: { level: "easy", label: "EU, full Schengen since 2024", detail: "Bulgaria joined Schengen for air/sea borders in 2024 and land borders in Jan 2025; as an EU/Belgian traveler there is no visa or border formality." },
        particular: { level: "easy", label: "Motorway vignette", detail: "A digital road tax vignette (e-vignette) is mandatory for all roads outside city limits, purchasable online or at border kiosks." },
        stayLength: { level: "easy", label: "Unlimited (EU citizen)", detail: "As an EU citizen, no stay limit applies for typical travel." },
        extendStay: { level: "easy", label: "Not applicable", detail: "No stay limit to extend as an EU national." },
        carnet: { level: "easy", label: "Not required", detail: "No carnet needed for an EU-registered vehicle." },
        vehicleStay: { level: "easy", label: "Unrestricted", detail: "No temporary import restriction for an EU-plated vehicle." },
        extendVeh: { level: "easy", label: "Not applicable", detail: "No vehicle stay limit exists." },
        modernVeh: { level: "moderate", label: "Fuel fine, sparse dealer network", detail: "Diesel is widely available and cheaper than Western Europe; Mercedes-Benz dealer presence exists mainly in Sofia/Plovdiv, more limited elsewhere." },
        roadQuality: { level: "moderate", label: "Mixed, improving", detail: "Main highways (Trakia, Hemus) are good; many secondary and mountain roads are poorly maintained with potholes." },
      },
    },
    { id: "HRV", iso: "HRV", name: "Croatia", lat: 44.49, lng: 16.52, continent: "Europe",
      climate: {
        codes: "OOOIIOVVOIIO",
        extra: ["", "", "", "", "", "T", "HT", "HT", "T", "", "", ""],
        note: "Best May-June and September; Dalmatian coast severely overtouristed July-August with intense heat.",
      },
      complexity: {
        visa: { level: "easy", label: "EU/Schengen since 2023", detail: "Croatia joined Schengen in January 2023; as an EU/Belgian traveler there is no visa or border check." },
        particular: { level: "easy", label: "No special permits", detail: "No mandatory guide or permits; standard EU travel rules apply." },
        stayLength: { level: "easy", label: "Unlimited (EU citizen)", detail: "No stay limit as an EU citizen." },
        extendStay: { level: "easy", label: "Not applicable", detail: "No stay limit to extend." },
        carnet: { level: "easy", label: "Not required", detail: "No carnet needed for an EU-registered vehicle." },
        vehicleStay: { level: "easy", label: "Unrestricted", detail: "No temporary import restriction for an EU-plated vehicle." },
        extendVeh: { level: "easy", label: "Not applicable", detail: "No vehicle stay limit exists." },
        modernVeh: { level: "easy", label: "Good fuel, decent dealer network", detail: "Diesel widely available; Mercedes-Benz dealers present in Zagreb, Split and Rijeka." },
        roadQuality: { level: "moderate", label: "Good coastal highway, congested in summer", detail: "The A1 motorway and coastal road are well-maintained but severely congested in July-August, especially around Split and toward the islands' ferry ports." },
      },
    },
    { id: "CZE", iso: "CZE", name: "Czech Republic", lat: 49.84, lng: 15.55, continent: "Europe",
      climate: {
        codes: "VVOOIIOOIIOV",
        extra: ["C", "C", "", "", "", "", "", "T", "", "", "", "C"],
        note: "Best May-June and September; Prague busy with tourists in summer, cold winters.",
      },
      complexity: {
        visa: { level: "easy", label: "EU/Schengen, no formality", detail: "No visa, no border checks between Belgium and Czechia." },
        particular: { level: "easy", label: "Motorway vignette", detail: "A digital motorway vignette is mandatory for highway use, purchasable online or at border stations." },
        stayLength: { level: "easy", label: "Unlimited (EU citizen)", detail: "No stay limit as an EU citizen." },
        extendStay: { level: "easy", label: "Not applicable", detail: "No stay limit to extend." },
        carnet: { level: "easy", label: "Not required", detail: "No carnet needed for an EU-registered vehicle." },
        vehicleStay: { level: "easy", label: "Unrestricted", detail: "No temporary import restriction for an EU-plated vehicle." },
        extendVeh: { level: "easy", label: "Not applicable", detail: "No vehicle stay limit exists." },
        modernVeh: { level: "easy", label: "Excellent, full dealer network", detail: "Full Mercedes-Benz dealer/service network including Prague, Brno and elsewhere; fuel quality is high." },
        roadQuality: { level: "easy", label: "Good, improving motorways", detail: "Motorway network is solid and expanding; secondary roads are generally in good condition." },
      },
    },
    { id: "DNK", iso: "DNK", name: "Denmark", lat: 56.27, lng: 10.39, continent: "Europe",
      climate: {
        codes: "OOOOIIIIIOOO",
        extra: ["", "", "", "", "", "", "", "", "", "", "", ""],
        note: "Mild year-round; best May-September, cool and windy in winter.",
      },
      complexity: {
        visa: { level: "easy", label: "EU/Schengen, no formality", detail: "No visa, no border checks between Belgium and Denmark." },
        particular: { level: "easy", label: "Bridge/tunnel tolls", detail: "The Great Belt and Öresund bridges charge tolls; otherwise no special permits." },
        stayLength: { level: "easy", label: "Unlimited (EU citizen)", detail: "No stay limit as an EU citizen." },
        extendStay: { level: "easy", label: "Not applicable", detail: "No stay limit to extend." },
        carnet: { level: "easy", label: "Not required", detail: "No carnet needed for an EU-registered vehicle." },
        vehicleStay: { level: "easy", label: "Unrestricted", detail: "No temporary import restriction for an EU-plated vehicle." },
        extendVeh: { level: "easy", label: "Not applicable", detail: "No vehicle stay limit exists." },
        modernVeh: { level: "easy", label: "Excellent, full dealer network", detail: "High fuel quality, full Mercedes-Benz service network nationwide." },
        roadQuality: { level: "easy", label: "Excellent", detail: "Roads are in excellent condition throughout; flat terrain, no mountain-pass concerns." },
      },
    },
    { id: "EST", iso: "EST", name: "Estonia", lat: 58.54, lng: 25.74, continent: "Europe",
      climate: {
        codes: "VVOOIIIIIOOV",
        extra: ["C", "C", "", "", "", "", "", "", "", "", "", "C"],
        note: "Best June-August; cold, dark, icy winters from November to March.",
      },
      complexity: {
        visa: { level: "easy", label: "EU/Schengen, no formality", detail: "No visa, no border checks between Belgium and Estonia." },
        particular: { level: "easy", label: "No special permits", detail: "No mandatory guide or permits for standard travel." },
        stayLength: { level: "easy", label: "Unlimited (EU citizen)", detail: "No stay limit as an EU citizen." },
        extendStay: { level: "easy", label: "Not applicable", detail: "No stay limit to extend." },
        carnet: { level: "easy", label: "Not required", detail: "No carnet needed for an EU-registered vehicle." },
        vehicleStay: { level: "easy", label: "Unrestricted", detail: "No temporary import restriction for an EU-plated vehicle." },
        extendVeh: { level: "easy", label: "Not applicable", detail: "No vehicle stay limit exists." },
        modernVeh: { level: "moderate", label: "Good fuel, sparser dealer network", detail: "Fuel quality is good; Mercedes-Benz dealer support concentrated in Tallinn, thinner elsewhere." },
        roadQuality: { level: "moderate", label: "Good main roads, icy in winter", detail: "Main roads are well-maintained; winter driving requires studded tires/caution due to ice and snow." },
      },
    },
    { id: "FIN", iso: "FIN", name: "Finland", lat: 65.01, lng: 26.08, continent: "Europe",
      climate: {
        codes: "VVOOIIIIIOOV",
        extra: ["C", "C", "", "", "", "", "", "", "", "", "", "C"],
        note: "Best June-August (midnight sun in the north); harsh, dark, snowy winters November-March.",
      },
      complexity: {
        visa: { level: "easy", label: "EU/Schengen, no formality", detail: "No visa, no border checks between Belgium and Finland." },
        particular: { level: "easy", label: "No special permits", detail: "No mandatory guide or permits; note Finland borders Russia and some border-zone roads/areas near it have restrictions." },
        stayLength: { level: "easy", label: "Unlimited (EU citizen)", detail: "No stay limit as an EU citizen." },
        extendStay: { level: "easy", label: "Not applicable", detail: "No stay limit to extend." },
        carnet: { level: "easy", label: "Not required", detail: "No carnet needed for an EU-registered vehicle." },
        vehicleStay: { level: "easy", label: "Unrestricted", detail: "No temporary import restriction for an EU-plated vehicle." },
        extendVeh: { level: "easy", label: "Not applicable", detail: "No vehicle stay limit exists." },
        modernVeh: { level: "easy", label: "Excellent, full dealer network", detail: "High-quality fuel and full Mercedes-Benz service network in major cities; winter-grade diesel used automatically in cold months." },
        roadQuality: { level: "easy", label: "Good, winter conditions common", detail: "Roads are well-maintained; winter driving requires snow tires and caution on rural roads in the north." },
      },
    },
    { id: "FRA", iso: "FRA", name: "France", lat: 46.26, lng: 2.48, continent: "Europe",
      climate: {
        codes: "OOOIIIVVIIOO",
        extra: ["", "", "", "", "", "T", "HT", "HT", "T", "", "", ""],
        note: "Best April-June and September-October; hot and very crowded coast/Riviera and Paris in July-August.",
      },
      complexity: {
        visa: { level: "easy", label: "EU/Schengen, no formality", detail: "No visa, no border checks between Belgium and France." },
        particular: { level: "easy", label: "Low-emission zones (Crit'Air)", detail: "Several French cities (Paris, Lyon, etc.) require a Crit'Air sticker for entry during restricted periods; a modern Euro6 Sprinter qualifies for the cleanest category." },
        stayLength: { level: "easy", label: "Unlimited (EU citizen)", detail: "No stay limit as an EU citizen." },
        extendStay: { level: "easy", label: "Not applicable", detail: "No stay limit to extend." },
        carnet: { level: "easy", label: "Not required", detail: "No carnet needed for an EU-registered vehicle." },
        vehicleStay: { level: "easy", label: "Unrestricted", detail: "No temporary import restriction for an EU-plated vehicle." },
        extendVeh: { level: "easy", label: "Not applicable", detail: "No vehicle stay limit exists." },
        modernVeh: { level: "easy", label: "Excellent, full dealer network", detail: "Dense Mercedes-Benz dealer network and high fuel quality throughout." },
        roadQuality: { level: "easy", label: "Excellent, tolled motorways", detail: "Extensive, well-maintained motorway network (with tolls); alpine passes can close seasonally in winter." },
      },
    },
    { id: "DEU", iso: "DEU", name: "Germany", lat: 51.14, lng: 10.5, continent: "Europe",
      climate: {
        codes: "VOOIIIOOIIOV",
        extra: ["C", "", "", "", "", "", "H", "", "", "", "", "C"],
        note: "Best May-June and September; mild, popular Christmas markets in winter, warm but sometimes crowded July-August.",
      },
      complexity: {
        visa: { level: "easy", label: "EU/Schengen, no formality", detail: "No visa, no border checks between Belgium and Germany." },
        particular: { level: "easy", label: "Umweltzone stickers", detail: "Many city centers require an Umweltplakette (environmental sticker); a Euro6 Sprinter automatically qualifies for the green sticker." },
        stayLength: { level: "easy", label: "Unlimited (EU citizen)", detail: "No stay limit as an EU citizen." },
        extendStay: { level: "easy", label: "Not applicable", detail: "No stay limit to extend." },
        carnet: { level: "easy", label: "Not required", detail: "No carnet needed for an EU-registered vehicle." },
        vehicleStay: { level: "easy", label: "Unrestricted", detail: "No temporary import restriction for an EU-plated vehicle." },
        extendVeh: { level: "easy", label: "Not applicable", detail: "No vehicle stay limit exists." },
        modernVeh: { level: "easy", label: "Best-in-class, home market for Mercedes", detail: "Mercedes-Benz's home market; dense dealer network and top fuel quality nationwide." },
        roadQuality: { level: "easy", label: "Excellent Autobahn network", detail: "Extensive, free, well-maintained Autobahn network; no toll for cars/vans, minimal seasonal restrictions." },
      },
    },
    { id: "GRC", iso: "GRC", name: "Greece", lat: 38.37, lng: 23.38, continent: "Europe",
      climate: {
        codes: "OOOIIVVVIIOO",
        extra: ["", "", "", "", "", "HT", "HT", "HT", "T", "", "", ""],
        note: "Best April-June and September-October; islands extremely overtouristed and scorching July-August.",
      },
      complexity: {
        visa: { level: "easy", label: "EU/Schengen, no formality", detail: "No visa, no border checks between Belgium and Greece." },
        particular: { level: "easy", label: "Ferries for islands", detail: "No special permits, but reaching islands requires vehicle ferries which should be booked ahead in high season." },
        stayLength: { level: "easy", label: "Unlimited (EU citizen)", detail: "No stay limit as an EU citizen." },
        extendStay: { level: "easy", label: "Not applicable", detail: "No stay limit to extend." },
        carnet: { level: "easy", label: "Not required", detail: "No carnet needed for an EU-registered vehicle." },
        vehicleStay: { level: "easy", label: "Unrestricted", detail: "No temporary import restriction for an EU-plated vehicle." },
        extendVeh: { level: "easy", label: "Not applicable", detail: "No vehicle stay limit exists." },
        modernVeh: { level: "moderate", label: "Fuel fine, dealer network mainland-focused", detail: "Diesel widely available; Mercedes-Benz dealers concentrated in Athens/Thessaloniki, more limited on islands." },
        roadQuality: { level: "moderate", label: "Good mainland, mountainous/island roads variable", detail: "Motorways are good and tolled; many mountain and island roads are narrow and winding, occasional summer wildfire road closures." },
      },
    },
    { id: "HUN", iso: "HUN", name: "Hungary", lat: 47.19, lng: 19.46, continent: "Europe",
      climate: {
        codes: "VOOIIOVVIIOV",
        extra: ["C", "", "", "", "", "", "H", "H", "", "", "", "C"],
        note: "Best May-June and September; hot, dry summers, cold winters.",
      },
      complexity: {
        visa: { level: "easy", label: "EU/Schengen, no formality", detail: "No visa, no border checks between Belgium and Hungary." },
        particular: { level: "easy", label: "e-Vignette required", detail: "An electronic motorway vignette is mandatory, purchasable online by license plate." },
        stayLength: { level: "easy", label: "Unlimited (EU citizen)", detail: "No stay limit as an EU citizen." },
        extendStay: { level: "easy", label: "Not applicable", detail: "No stay limit to extend." },
        carnet: { level: "easy", label: "Not required", detail: "No carnet needed for an EU-registered vehicle." },
        vehicleStay: { level: "easy", label: "Unrestricted", detail: "No temporary import restriction for an EU-plated vehicle." },
        extendVeh: { level: "easy", label: "Not applicable", detail: "No vehicle stay limit exists." },
        modernVeh: { level: "easy", label: "Good fuel, solid dealer network", detail: "Good fuel quality; Mercedes-Benz dealer presence in Budapest and other major cities." },
        roadQuality: { level: "easy", label: "Good", detail: "Motorways and main roads are in good condition throughout." },
      },
    },
    { id: "ISL", iso: "ISL", name: "Iceland", lat: 65.01, lng: -18.97, continent: "Europe",
      climate: {
        codes: "VVOOIIIIIOOV",
        extra: ["C", "C", "", "", "", "T", "T", "T", "T", "", "", "C"],
        note: "Best June-August for full Ring Road access, but this is also extreme high season; shoulder months (May, Sept) quieter with more limited highland access. Winter brings ice, storms and limited daylight.",
      },
      complexity: {
        visa: { level: "easy", label: "EU/Schengen-associated, no formality", detail: "Iceland is part of Schengen (EFTA); no visa, no border checks for EU/Belgian travelers." },
        particular: { level: "moderate", label: "F-road/highland restrictions", detail: "Interior F-roads require 4x4 and are only open roughly June-September depending on conditions; a standard Sprinter camper (even AWD) may be unsuitable or restricted on unbridged river crossings — check road.is before planning highland routes." },
        stayLength: { level: "easy", label: "Unlimited (EU/EFTA citizen)", detail: "No stay limit as an EU citizen within the Schengen/EFTA framework." },
        extendStay: { level: "easy", label: "Not applicable", detail: "No stay limit to extend." },
        carnet: { level: "easy", label: "Not required, ferry-only access", detail: "No land border exists — vehicle arrives via car ferry (Smyril Line, Denmark/Faroe Islands route) or air freight; no carnet needed for an EU-registered vehicle, only ferry booking and customs declaration." },
        vehicleStay: { level: "easy", label: "Unrestricted", detail: "No temporary import restriction for an EU-plated vehicle arriving by ferry." },
        extendVeh: { level: "easy", label: "Not applicable", detail: "No vehicle stay limit exists." },
        modernVeh: { level: "moderate", label: "Good fuel, one Mercedes dealer (Reykjavik)", detail: "Diesel is widely available and good quality; the only official Mercedes-Benz dealer/service center is in Reykjavik, so plan repairs around the capital area." },
        roadQuality: { level: "moderate", label: "Ring Road good, weather-dependent", detail: "Route 1 (Ring Road) is paved and well-maintained; strong winds, sudden weather changes, and gravel sections in the east/highlands demand caution, especially outside summer." },
      },
    },
    { id: "IRL", iso: "IRL", name: "Ireland", lat: 53.4, lng: -8.01, continent: "Europe",
      climate: {
        codes: "OOOOIIIIIOOO",
        extra: ["", "", "", "", "", "", "", "", "", "", "", ""],
        note: "Mild, wet year-round; best May-September for driest weather.",
      },
      complexity: {
        visa: { level: "easy", label: "EU, outside Schengen but no visa", detail: "Ireland is EU but not in Schengen; as a Belgian/EU citizen you still need no visa and face minimal border formality (immigration control exists but is fast for EU passports)." },
        particular: { level: "easy", label: "Drive on the left", detail: "Ireland drives on the left; only real adjustment needed, no special permits." },
        stayLength: { level: "easy", label: "Unlimited (EU citizen)", detail: "No stay limit as an EU citizen exercising free movement rights." },
        extendStay: { level: "easy", label: "Not applicable", detail: "No stay limit to extend." },
        carnet: { level: "easy", label: "Not required", detail: "No carnet needed for an EU-registered vehicle; ferry crossing required from France/UK as there's no land border to continental Europe." },
        vehicleStay: { level: "easy", label: "Unrestricted", detail: "No temporary import restriction for an EU-plated vehicle." },
        extendVeh: { level: "easy", label: "Not applicable", detail: "No vehicle stay limit exists." },
        modernVeh: { level: "easy", label: "Good fuel, decent dealer network", detail: "Good fuel quality and availability; Mercedes-Benz dealers present in Dublin, Cork and other cities." },
        roadQuality: { level: "moderate", label: "Good main roads, narrow rural lanes", detail: "Motorways and national routes are in good condition; many scenic rural roads (e.g. Wild Atlantic Way) are narrow with tight hedgerows, challenging for a full-size Sprinter." },
      },
    },
    { id: "ITA", iso: "ITA", name: "Italy", lat: 41.87, lng: 12.62, continent: "Europe",
      climate: {
        codes: "OOOIIVVVIIOO",
        extra: ["", "", "", "", "", "HT", "HT", "HT", "T", "", "", ""],
        note: "Best April-June and September-October; extreme heat and severe overtourism (Venice, Cinque Terre, Amalfi) July-August.",
      },
      complexity: {
        visa: { level: "easy", label: "EU/Schengen, no formality", detail: "No visa, no border checks between Belgium and Italy." },
        particular: { level: "moderate", label: "ZTL zones, ferry for islands", detail: "Many historic city centers have ZTL (limited traffic zones) with automatic cameras and fines for unauthorized entry; check before driving into old towns. Ferries needed for Sicily/Sardinia." },
        stayLength: { level: "easy", label: "Unlimited (EU citizen)", detail: "No stay limit as an EU citizen." },
        extendStay: { level: "easy", label: "Not applicable", detail: "No stay limit to extend." },
        carnet: { level: "easy", label: "Not required", detail: "No carnet needed for an EU-registered vehicle." },
        vehicleStay: { level: "easy", label: "Unrestricted", detail: "No temporary import restriction for an EU-plated vehicle." },
        extendVeh: { level: "easy", label: "Not applicable", detail: "No vehicle stay limit exists." },
        modernVeh: { level: "easy", label: "Excellent, full dealer network", detail: "Full Mercedes-Benz dealer network and high fuel quality nationwide." },
        roadQuality: { level: "moderate", label: "Good motorways, tight historic towns", detail: "Autostrade are excellent (tolled); historic town centers have very narrow streets unsuitable for a Sprinter, and mountain passes in the Alps/Apennines can close in winter." },
      },
    },
    { id: "LVA", iso: "LVA", name: "Latvia", lat: 56.79, lng: 24.62, continent: "Europe",
      climate: {
        codes: "VVOOIIIIIOOV",
        extra: ["C", "C", "", "", "", "", "", "", "", "", "", "C"],
        note: "Best June-August; cold, icy winters from November to March.",
      },
      complexity: {
        visa: { level: "easy", label: "EU/Schengen, no formality", detail: "No visa, no border checks between Belgium and Latvia." },
        particular: { level: "easy", label: "No special permits", detail: "No mandatory guide or permits for standard travel." },
        stayLength: { level: "easy", label: "Unlimited (EU citizen)", detail: "No stay limit as an EU citizen." },
        extendStay: { level: "easy", label: "Not applicable", detail: "No stay limit to extend." },
        carnet: { level: "easy", label: "Not required", detail: "No carnet needed for an EU-registered vehicle." },
        vehicleStay: { level: "easy", label: "Unrestricted", detail: "No temporary import restriction for an EU-plated vehicle." },
        extendVeh: { level: "easy", label: "Not applicable", detail: "No vehicle stay limit exists." },
        modernVeh: { level: "moderate", label: "Good fuel, sparser dealer network", detail: "Fuel quality is fine; Mercedes-Benz dealer support concentrated in Riga." },
        roadQuality: { level: "moderate", label: "Good main roads, icy in winter", detail: "Main roads are decent; rural roads can be rough and winter driving requires caution for ice." },
      },
    },
    { id: "LTU", iso: "LTU", name: "Lithuania", lat: 55.14, lng: 23.82, continent: "Europe",
      climate: {
        codes: "VVOOIIIIIOOV",
        extra: ["C", "C", "", "", "", "", "", "", "", "", "", "C"],
        note: "Best June-August; cold winters November-March.",
      },
      complexity: {
        visa: { level: "easy", label: "EU/Schengen, no formality", detail: "No visa, no border checks between Belgium and Lithuania." },
        particular: { level: "easy", label: "No special permits", detail: "No mandatory guide or permits; note the Kaliningrad (Russia) transit route nearby has separate rules if approaching that border." },
        stayLength: { level: "easy", label: "Unlimited (EU citizen)", detail: "No stay limit as an EU citizen." },
        extendStay: { level: "easy", label: "Not applicable", detail: "No stay limit to extend." },
        carnet: { level: "easy", label: "Not required", detail: "No carnet needed for an EU-registered vehicle." },
        vehicleStay: { level: "easy", label: "Unrestricted", detail: "No temporary import restriction for an EU-plated vehicle." },
        extendVeh: { level: "easy", label: "Not applicable", detail: "No vehicle stay limit exists." },
        modernVeh: { level: "moderate", label: "Good fuel, sparser dealer network", detail: "Fuel quality is fine; Mercedes-Benz dealer support concentrated in Vilnius." },
        roadQuality: { level: "easy", label: "Good main roads", detail: "Main highways are in good condition; winter driving requires caution for ice/snow." },
      },
    },
    { id: "LUX", iso: "LUX", name: "Luxembourg", lat: 49.79, lng: 5.96, continent: "Europe",
      climate: {
        codes: "OOOOIIIIIOOO",
        extra: ["", "", "", "", "", "", "", "", "", "", "", ""],
        note: "Mild year-round; best May-September.",
      },
      complexity: {
        visa: { level: "easy", label: "EU/Schengen, no formality", detail: "No visa, no border checks between Belgium and Luxembourg." },
        particular: { level: "easy", label: "Cheap fuel", detail: "No special permits; fuel prices are notably lower than neighboring countries, worth fueling up here." },
        stayLength: { level: "easy", label: "Unlimited (EU citizen)", detail: "No stay limit as an EU citizen." },
        extendStay: { level: "easy", label: "Not applicable", detail: "No stay limit to extend." },
        carnet: { level: "easy", label: "Not required", detail: "No carnet needed for an EU-registered vehicle." },
        vehicleStay: { level: "easy", label: "Unrestricted", detail: "No temporary import restriction for an EU-plated vehicle." },
        extendVeh: { level: "easy", label: "Not applicable", detail: "No vehicle stay limit exists." },
        modernVeh: { level: "easy", label: "Excellent, full dealer network", detail: "Full Mercedes-Benz dealer network; cheap, high-quality fuel." },
        roadQuality: { level: "easy", label: "Excellent", detail: "Small country with an excellent, well-maintained road network throughout." },
      },
    },
    { id: "MDA", iso: "MDA", name: "Moldova", lat: 46.98, lng: 28.32, continent: "Europe",
      climate: {
        codes: "OOOIIOVVIIOO",
        extra: ["", "", "", "", "", "", "H", "H", "", "", "", ""],
        note: "Best May-June and September; hot, dry summers, cold winters.",
      },
      complexity: {
        visa: { level: "easy", label: "Visa-free, non-Schengen", detail: "EU/Belgian citizens enter visa-free for up to 90 days in 180 days; separate passport stamps apply as it's outside Schengen." },
        particular: { level: "moderate", label: "Transnistria caution", detail: "The breakaway region of Transnistria has its own de facto border/registration procedure and is generally best avoided or entered only briefly with caution; the rest of Moldova has no special permits." },
        stayLength: { level: "easy", label: "90 days", detail: "Standard tourist stay allowance is 90 days within 180 days." },
        extendStay: { level: "moderate", label: "Possible via immigration bureau", detail: "Extensions require application at the Bureau for Migration and Asylum; not routine for short tourist stays." },
        carnet: { level: "easy", label: "Not required", detail: "No carnet needed; a temporary import stamp/customs declaration is given at the border free of charge." },
        vehicleStay: { level: "easy", label: "Matches 90-day stay", detail: "Vehicle import period is tied to the traveler's 90-day allowance." },
        extendVeh: { level: "moderate", label: "Tied to visa extension", detail: "Extending vehicle stay requires the same process as a personal stay extension." },
        modernVeh: { level: "moderate", label: "Adequate fuel, no dealer network", detail: "Diesel is available but quality can be variable in rural areas; no official Mercedes-Benz dealer, nearest full service in Romania." },
        roadQuality: { level: "moderate", label: "Poor to fair outside main routes", detail: "The Chisinau-area roads are reasonable; many rural roads are poorly maintained with potholes." },
      },
    },
    { id: "MNE", iso: "MNE", name: "Montenegro", lat: 42.7, lng: 19.39, continent: "Europe",
      climate: {
        codes: "OOOIIOVVIIOO",
        extra: ["", "", "", "", "", "T", "HT", "HT", "T", "", "", ""],
        note: "Best May-June and September; hot and busy coastline (Kotor, Budva) July-August.",
      },
      complexity: {
        visa: { level: "easy", label: "Visa-free, non-Schengen", detail: "EU/Belgian citizens enter visa-free for up to 90 days in 180 days; separate passport stamps as it's outside Schengen (though Montenegro is a Schengen candidate country)." },
        particular: { level: "easy", label: "No special permits", detail: "No mandatory guide or region permits for standard tourist/overland travel." },
        stayLength: { level: "easy", label: "90 days", detail: "Standard tourist stay allowance is 90 days within 180 days." },
        extendStay: { level: "moderate", label: "Possible via local police", detail: "Extensions require application at a local police administration office; not routine for short-term tourists." },
        carnet: { level: "easy", label: "Not required", detail: "No carnet needed; a temporary import stamp is given at the border free of charge." },
        vehicleStay: { level: "easy", label: "Matches 90-day stay", detail: "Vehicle import period is tied to the traveler's 90-day allowance." },
        extendVeh: { level: "moderate", label: "Tied to visa extension", detail: "Extending vehicle stay requires the same process as a personal stay extension." },
        modernVeh: { level: "moderate", label: "Fuel fine, no dealer network", detail: "Diesel is widely available; no official Mercedes-Benz dealer in-country, nearest full service typically in Croatia or Serbia." },
        roadQuality: { level: "moderate", label: "Mountainous, narrow coastal roads", detail: "The coastal road (Kotor Bay area) is narrow, winding and extremely congested in summer; interior mountain roads are scenic but slow and can be affected by rockfall/landslides." },
      },
    },
    { id: "NLD", iso: "NLD", name: "Netherlands", lat: 52.16, lng: 5.2, continent: "Europe",
      climate: {
        codes: "OOOOIIIIIOOO",
        extra: ["", "", "", "", "", "", "", "T", "", "", "", ""],
        note: "Mild year-round; best May-September, Amsterdam can be crowded in summer.",
      },
      complexity: {
        visa: { level: "easy", label: "EU/Schengen, no formality", detail: "No visa, no border checks between Belgium and the Netherlands." },
        particular: { level: "easy", label: "Amsterdam LEZ, environmental zones", detail: "Some cities including Amsterdam have low-emission zones; a Euro6 Sprinter qualifies without issue." },
        stayLength: { level: "easy", label: "Unlimited (EU citizen)", detail: "No stay limit as an EU citizen." },
        extendStay: { level: "easy", label: "Not applicable", detail: "No stay limit to extend." },
        carnet: { level: "easy", label: "Not required", detail: "No carnet needed for an EU-registered vehicle." },
        vehicleStay: { level: "easy", label: "Unrestricted", detail: "No temporary import restriction for an EU-plated vehicle." },
        extendVeh: { level: "easy", label: "Not applicable", detail: "No vehicle stay limit exists." },
        modernVeh: { level: "easy", label: "Excellent, full dealer network", detail: "Full Mercedes-Benz dealer network and high fuel quality throughout." },
        roadQuality: { level: "easy", label: "Excellent", detail: "Dense, well-maintained road network throughout; flat terrain, no mountain-pass concerns." },
      },
    },
    { id: "MKD", iso: "MKD", name: "North Macedonia", lat: 41.58, lng: 21.71, continent: "Europe",
      climate: {
        codes: "OOOIIVVVIIOO",
        extra: ["", "", "", "", "", "H", "H", "H", "", "", "", ""],
        note: "Best April-June and September-October; hot, dry summers with continental heat inland.",
      },
      complexity: {
        visa: { level: "easy", label: "Visa-free, non-Schengen", detail: "EU/Belgian citizens enter visa-free for up to 90 days in 180 days; separate passport stamps as it's outside Schengen (candidate country)." },
        particular: { level: "easy", label: "No special permits", detail: "No mandatory guide or region permits for standard travel." },
        stayLength: { level: "easy", label: "90 days", detail: "Standard tourist stay allowance is 90 days within 180 days." },
        extendStay: { level: "moderate", label: "Possible via Ministry of Interior", detail: "Extensions require application at the Ministry of Interior; not routine, easier to exit/re-enter via a neighboring country." },
        carnet: { level: "easy", label: "Not required", detail: "No carnet needed; a temporary import stamp is given at the border free of charge." },
        vehicleStay: { level: "easy", label: "Matches 90-day stay", detail: "Vehicle import period is tied to the traveler's 90-day allowance." },
        extendVeh: { level: "moderate", label: "Tied to visa extension", detail: "Extending vehicle stay requires the same process as a personal stay extension." },
        modernVeh: { level: "moderate", label: "Fuel fine, no dealer network", detail: "Diesel is widely available; no official Mercedes-Benz dealer, nearest full service typically in Greece or Serbia." },
        roadQuality: { level: "moderate", label: "Fair, mountainous interior", detail: "Main highways (e.g. toward Skopje) are decent; mountain roads are narrow and winding, with occasional winter closures." },
      },
    },
    { id: "NOR", iso: "NOR", name: "Norway", lat: 69.37, lng: 18.14, continent: "Europe",
      climate: {
        codes: "VVOOIIIIIOOV",
        extra: ["C", "C", "", "", "", "T", "T", "T", "", "", "", "C"],
        note: "Best June-August for full fjord/mountain-road access, also busiest season; many mountain passes closed October-May due to snow.",
      },
      complexity: {
        visa: { level: "easy", label: "EU/Schengen-associated, no formality", detail: "Norway is an EFTA/Schengen member; no visa, no border checks for EU/Belgian travelers." },
        particular: { level: "easy", label: "Toll roads, ferries", detail: "Extensive electronic road tolling (AutoPASS) applies automatically; many fjord routes require ferries, which should be timed/booked in high season." },
        stayLength: { level: "easy", label: "Unlimited (EU/EFTA citizen)", detail: "No stay limit as an EU citizen within Schengen/EFTA." },
        extendStay: { level: "easy", label: "Not applicable", detail: "No stay limit to extend." },
        carnet: { level: "easy", label: "Not required", detail: "No carnet needed for an EU-registered vehicle." },
        vehicleStay: { level: "easy", label: "Unrestricted", detail: "No temporary import restriction for an EU-plated vehicle." },
        extendVeh: { level: "easy", label: "Not applicable", detail: "No vehicle stay limit exists." },
        modernVeh: { level: "easy", label: "Excellent, full dealer network", detail: "High fuel quality and full Mercedes-Benz service network in major cities, though remote and expensive fuel/service in far north." },
        roadQuality: { level: "moderate", label: "Good but seasonal, mountain passes close", detail: "Roads are well-engineered (tunnels, bridges) but many high mountain passes and some fjord roads close from October to May/June due to snow; check statens vegvesen for current status." },
      },
    },
    { id: "POL", iso: "POL", name: "Poland", lat: 51.94, lng: 19.05, continent: "Europe",
      climate: {
        codes: "VOOIIOOOIIOV",
        extra: ["C", "", "", "", "", "", "H", "", "", "", "", "C"],
        note: "Best May-June and September; warm summers, cold winters.",
      },
      complexity: {
        visa: { level: "easy", label: "EU/Schengen, no formality", detail: "No visa, no border checks between Belgium and Poland." },
        particular: { level: "easy", label: "No special permits", detail: "No mandatory guide or permits for standard travel." },
        stayLength: { level: "easy", label: "Unlimited (EU citizen)", detail: "No stay limit as an EU citizen." },
        extendStay: { level: "easy", label: "Not applicable", detail: "No stay limit to extend." },
        carnet: { level: "easy", label: "Not required", detail: "No carnet needed for an EU-registered vehicle." },
        vehicleStay: { level: "easy", label: "Unrestricted", detail: "No temporary import restriction for an EU-plated vehicle." },
        extendVeh: { level: "easy", label: "Not applicable", detail: "No vehicle stay limit exists." },
        modernVeh: { level: "easy", label: "Good fuel, solid dealer network", detail: "Good fuel quality; Mercedes-Benz dealer network present in major cities." },
        roadQuality: { level: "easy", label: "Good, rapidly improved motorways", detail: "Motorway network has expanded significantly; main roads are in good condition throughout." },
      },
    },
    { id: "PRT", iso: "PRT", name: "Portugal", lat: 39.56, lng: -7.96, continent: "Europe",
      climate: {
        codes: "OOOIIVVVIIOO",
        extra: ["", "", "", "", "", "T", "HT", "HT", "T", "", "", ""],
        note: "Best April-June and September-October; Lisbon and Algarve coast very hot and overtouristed July-August.",
      },
      complexity: {
        visa: { level: "easy", label: "EU/Schengen, no formality", detail: "No visa, no border checks between Belgium and Portugal." },
        particular: { level: "easy", label: "No special permits", detail: "No mandatory guide or permits; note some coastal municipalities restrict overnight motorhome parking, though not driving." },
        stayLength: { level: "easy", label: "Unlimited (EU citizen)", detail: "No stay limit as an EU citizen." },
        extendStay: { level: "easy", label: "Not applicable", detail: "No stay limit to extend." },
        carnet: { level: "easy", label: "Not required", detail: "No carnet needed for an EU-registered vehicle." },
        vehicleStay: { level: "easy", label: "Unrestricted", detail: "No temporary import restriction for an EU-plated vehicle." },
        extendVeh: { level: "easy", label: "Not applicable", detail: "No vehicle stay limit exists." },
        modernVeh: { level: "easy", label: "Good fuel, decent dealer network", detail: "Good fuel quality; Mercedes-Benz dealers present in Lisbon and Porto." },
        roadQuality: { level: "easy", label: "Good, tolled motorways", detail: "Motorway network (with electronic tolls) is excellent; secondary roads in rural/mountain areas are decent but narrower." },
      },
    },
    { id: "ROU", iso: "ROU", name: "Romania", lat: 45.95, lng: 24.92, continent: "Europe",
      climate: {
        codes: "VOOIIOVVIIOV",
        extra: ["C", "", "", "", "", "", "H", "H", "", "", "", "C"],
        note: "Best May-June and September; hot summers, cold winters, mountain passes can close.",
      },
      complexity: {
        visa: { level: "easy", label: "EU, full Schengen since 2025", detail: "Romania completed Schengen accession (land borders) in Jan 2025; as an EU/Belgian traveler there is no visa or border check." },
        particular: { level: "easy", label: "Rovinieta vignette", detail: "A rovinieta (road tax vignette) is mandatory for all public roads, purchasable online or at border/petrol stations." },
        stayLength: { level: "easy", label: "Unlimited (EU citizen)", detail: "No stay limit as an EU citizen." },
        extendStay: { level: "easy", label: "Not applicable", detail: "No stay limit to extend." },
        carnet: { level: "easy", label: "Not required", detail: "No carnet needed for an EU-registered vehicle." },
        vehicleStay: { level: "easy", label: "Unrestricted", detail: "No temporary import restriction for an EU-plated vehicle." },
        extendVeh: { level: "easy", label: "Not applicable", detail: "No vehicle stay limit exists." },
        modernVeh: { level: "moderate", label: "Fuel fine, dealer network in cities", detail: "Diesel widely available; Mercedes-Benz dealer presence in Bucharest and other major cities, thinner in rural areas." },
        roadQuality: { level: "moderate", label: "Mixed, mountain roads seasonal", detail: "Motorway network is still developing though improving fast; the Transfagarasan and other high mountain roads close in winter (roughly Oct-June)." },
      },
    },
    { id: "SRB", iso: "SRB", name: "Serbia", lat: 44.21, lng: 20.91, continent: "Europe",
      climate: {
        codes: "OOOIIOVVIIOO",
        extra: ["", "", "", "", "", "", "H", "H", "", "", "", ""],
        note: "Best May-June and September; hot, dry summers, cold winters.",
      },
      complexity: {
        visa: { level: "easy", label: "Visa-free, non-Schengen", detail: "EU/Belgian citizens enter visa-free for up to 90 days in 180 days; separate passport stamps as it's outside Schengen (candidate country)." },
        particular: { level: "easy", label: "No special permits", detail: "No mandatory guide or region permits for standard travel; note Kosovo border crossing rules can be complex if combining trips (entering Serbia after Kosovo via a non-Serbian border may be required)." },
        stayLength: { level: "easy", label: "90 days", detail: "Standard tourist stay allowance is 90 days within 180 days." },
        extendStay: { level: "moderate", label: "Possible via police administration", detail: "Extensions require application at a local police administration; not routine, easier to exit/re-enter via a neighboring country." },
        carnet: { level: "easy", label: "Not required", detail: "No carnet needed; a temporary import stamp is given at the border free of charge." },
        vehicleStay: { level: "easy", label: "Matches 90-day stay", detail: "Vehicle import period is tied to the traveler's 90-day allowance." },
        extendVeh: { level: "moderate", label: "Tied to visa extension", detail: "Extending vehicle stay requires the same process as a personal stay extension." },
        modernVeh: { level: "moderate", label: "Fuel fine, dealer network in Belgrade", detail: "Diesel widely available; Mercedes-Benz dealer presence in Belgrade and Novi Sad, thinner elsewhere." },
        roadQuality: { level: "moderate", label: "Good main routes, rural roads variable", detail: "Motorways (e.g. Corridor 10) are good; secondary and rural roads can be poorly maintained." },
      },
    },
    { id: "SVK", iso: "SVK", name: "Slovakia", lat: 48.67, lng: 19.72, continent: "Europe",
      climate: {
        codes: "VVOOIIOOIIOV",
        extra: ["C", "C", "", "", "", "", "H", "", "", "", "", "C"],
        note: "Best May-June and September; cold winters especially in Tatra mountains.",
      },
      complexity: {
        visa: { level: "easy", label: "EU/Schengen, no formality", detail: "No visa, no border checks between Belgium and Slovakia." },
        particular: { level: "easy", label: "Motorway vignette", detail: "A digital motorway vignette (e-known) is mandatory, purchasable online or at petrol stations." },
        stayLength: { level: "easy", label: "Unlimited (EU citizen)", detail: "No stay limit as an EU citizen." },
        extendStay: { level: "easy", label: "Not applicable", detail: "No stay limit to extend." },
        carnet: { level: "easy", label: "Not required", detail: "No carnet needed for an EU-registered vehicle." },
        vehicleStay: { level: "easy", label: "Unrestricted", detail: "No temporary import restriction for an EU-plated vehicle." },
        extendVeh: { level: "easy", label: "Not applicable", detail: "No vehicle stay limit exists." },
        modernVeh: { level: "moderate", label: "Good fuel, dealer network in cities", detail: "Good fuel quality; Mercedes-Benz dealer presence in Bratislava and other larger cities." },
        roadQuality: { level: "moderate", label: "Good main roads, mountain roads seasonal", detail: "Main highways are good; Tatra mountain roads can be affected by snow/ice in winter." },
      },
    },
    { id: "SVN", iso: "SVN", name: "Slovenia", lat: 46.15, lng: 15.13, continent: "Europe",
      climate: {
        codes: "OOOIIOVVIIOO",
        extra: ["", "", "", "", "", "", "H", "HT", "", "", "", ""],
        note: "Best May-June and September; warm summers with busy Lake Bled/coast in August.",
      },
      complexity: {
        visa: { level: "easy", label: "EU/Schengen, no formality", detail: "No visa, no border checks between Belgium and Slovenia." },
        particular: { level: "easy", label: "Motorway vignette", detail: "A physical or digital motorway vignette is mandatory, purchasable at borders/petrol stations." },
        stayLength: { level: "easy", label: "Unlimited (EU citizen)", detail: "No stay limit as an EU citizen." },
        extendStay: { level: "easy", label: "Not applicable", detail: "No stay limit to extend." },
        carnet: { level: "easy", label: "Not required", detail: "No carnet needed for an EU-registered vehicle." },
        vehicleStay: { level: "easy", label: "Unrestricted", detail: "No temporary import restriction for an EU-plated vehicle." },
        extendVeh: { level: "easy", label: "Not applicable", detail: "No vehicle stay limit exists." },
        modernVeh: { level: "easy", label: "Good fuel, decent dealer network", detail: "Good fuel quality; Mercedes-Benz dealer presence in Ljubljana." },
        roadQuality: { level: "easy", label: "Good, alpine roads seasonal", detail: "Main roads and motorways are well-maintained; some alpine passes (e.g. Vršič) close in winter." },
      },
    },
    { id: "ESP", iso: "ESP", name: "Spain", lat: 39.85, lng: -3.18, continent: "Europe",
      climate: {
        codes: "OOOIIVVVIIOO",
        extra: ["", "", "", "", "", "T", "HT", "HT", "T", "", "", ""],
        note: "Best April-June and September-October; interior/south extremely hot and coasts/Barcelona overtouristed July-August.",
      },
      complexity: {
        visa: { level: "easy", label: "EU/Schengen, no formality", detail: "No visa, no border checks between Belgium and Spain." },
        particular: { level: "easy", label: "Low-emission zones (Madrid, Barcelona)", detail: "Madrid and Barcelona have low-emission zones; a Euro6 Sprinter qualifies without issue." },
        stayLength: { level: "easy", label: "Unlimited (EU citizen)", detail: "No stay limit as an EU citizen." },
        extendStay: { level: "easy", label: "Not applicable", detail: "No stay limit to extend." },
        carnet: { level: "easy", label: "Not required", detail: "No carnet needed for an EU-registered vehicle." },
        vehicleStay: { level: "easy", label: "Unrestricted", detail: "No temporary import restriction for an EU-plated vehicle." },
        extendVeh: { level: "easy", label: "Not applicable", detail: "No vehicle stay limit exists." },
        modernVeh: { level: "easy", label: "Excellent, full dealer network", detail: "Full Mercedes-Benz dealer network and high fuel quality throughout." },
        roadQuality: { level: "easy", label: "Excellent, tolled/free motorways", detail: "Extensive, well-maintained motorway network; occasional Pyrenees pass closures in deep winter." },
      },
    },
    { id: "SWE", iso: "SWE", name: "Sweden", lat: 62.23, lng: 17.47, continent: "Europe",
      climate: {
        codes: "VVOOIIIIIOOV",
        extra: ["C", "C", "", "", "", "", "", "", "", "", "", "C"],
        note: "Best June-August (midnight sun in the north); long, cold, dark winters November-March.",
      },
      complexity: {
        visa: { level: "easy", label: "EU/Schengen, no formality", detail: "No visa, no border checks between Belgium and Sweden." },
        particular: { level: "easy", label: "No special permits", detail: "No mandatory guide or permits for standard travel." },
        stayLength: { level: "easy", label: "Unlimited (EU citizen)", detail: "No stay limit as an EU citizen." },
        extendStay: { level: "easy", label: "Not applicable", detail: "No stay limit to extend." },
        carnet: { level: "easy", label: "Not required", detail: "No carnet needed for an EU-registered vehicle." },
        vehicleStay: { level: "easy", label: "Unrestricted", detail: "No temporary import restriction for an EU-plated vehicle." },
        extendVeh: { level: "easy", label: "Not applicable", detail: "No vehicle stay limit exists." },
        modernVeh: { level: "easy", label: "Excellent, full dealer network", detail: "High-quality fuel and full Mercedes-Benz service network in major cities, sparser in the far north." },
        roadQuality: { level: "easy", label: "Excellent, winter conditions common", detail: "Roads are well-maintained; winter driving requires snow tires and caution, especially in the north." },
      },
    },
    { id: "CHE", iso: "CHE", name: "Switzerland", lat: 46.8, lng: 8.23, continent: "Europe",
      climate: {
        codes: "VVOIIOOOIIOV",
        extra: ["C", "C", "", "", "", "", "H", "T", "", "", "", "C"],
        note: "Best May-June and September; alpine passes can close in winter with heavy snow, summer busy in Alpine towns.",
      },
      complexity: {
        visa: { level: "easy", label: "EFTA/Schengen, no formality", detail: "Switzerland is not EU but is Schengen/EFTA; no visa, no border checks for EU/Belgian travelers, though customs spot-checks can occur since it's outside the EU customs union." },
        particular: { level: "moderate", label: "Motorway vignette, customs on goods", detail: "An annual highway vignette (sticker or digital) is mandatory; since Switzerland is outside the EU customs union, duty-free allowances apply for goods carried (e.g. fuel in jerry cans, alcohol, food)." },
        stayLength: { level: "easy", label: "Unlimited (EU citizen)", detail: "As an EU citizen under the EU-Switzerland free movement agreement, no stay limit applies for typical travel." },
        extendStay: { level: "easy", label: "Not applicable", detail: "No stay limit to extend." },
        carnet: { level: "easy", label: "Not required", detail: "No carnet needed for an EU-registered vehicle; standard customs declaration only applies to goods, not the vehicle itself." },
        vehicleStay: { level: "easy", label: "Unrestricted", detail: "No temporary import restriction for an EU-plated vehicle." },
        extendVeh: { level: "easy", label: "Not applicable", detail: "No vehicle stay limit exists." },
        modernVeh: { level: "easy", label: "Excellent, full dealer network", detail: "High fuel quality (though relatively expensive) and full Mercedes-Benz service network nationwide." },
        roadQuality: { level: "moderate", label: "Excellent but seasonal passes", detail: "Roads are superbly maintained; many high alpine passes close from around October/November to May/June, with car-carrying train tunnels as an alternative (e.g. Furka)." },
      },
    },
    { id: "UKR", iso: "UKR", name: "Ukraine", lat: 48.35, lng: 31.08, continent: "Europe",
      climate: {
        codes: "VVVVVVVVVVVV",
        extra: ["", "", "", "", "", "", "H", "H", "", "", "", ""],
        note: "Active war zone since February 2022 — overland tourist travel is not advisable or realistically possible in most of the country regardless of season; entry is restricted and dangerous.",
      },
      complexity: {
        visa: { level: "hard", label: "Not recommended, active war", detail: "Ukraine has been under martial law since Russia's February 2022 invasion; general tourist visa-free entry technically exists for EU citizens for up to 90 days, but this is entirely moot given the security situation. Overland travel for tourism is strongly advised against by essentially all governments." },
        particular: { level: "hard", label: "Active conflict, martial law", detail: "Air raid alerts, missile/drone strikes, martial law curfews, and closed military zones apply nationally; male Ukrainian citizens 18-60 face conscription/exit restrictions (not relevant to a foreign traveler, but reflects the environment). This is not a viable overland tourist destination currently." },
        stayLength: { level: "hard", label: "N/A given circumstances", detail: "Not meaningfully applicable while martial law and war conditions persist." },
        extendStay: { level: "hard", label: "N/A given circumstances", detail: "Not meaningfully applicable currently." },
        carnet: { level: "hard", label: "N/A given circumstances", detail: "Border crossing procedures exist in principle (no carnet historically required) but are irrelevant given current travel advisories against entry." },
        vehicleStay: { level: "hard", label: "N/A given circumstances", detail: "Not meaningfully applicable currently." },
        extendVeh: { level: "hard", label: "N/A given circumstances", detail: "Not meaningfully applicable currently." },
        modernVeh: { level: "hard", label: "Fuel shortages, infrastructure damaged", detail: "Fuel supply has been disrupted at times by the war; Mercedes-Benz dealer support is severely degraded/unavailable in many regions. Not recommended to bring a vehicle in currently." },
        roadQuality: { level: "hard", label: "War damage, mines, active danger", detail: "Roads and bridges have been damaged by fighting in many regions; landmines and unexploded ordnance are a serious risk well beyond the immediate front line. Do not attempt overland travel here under current conditions." },
      },
    },
    { id: "GBR", iso: "GBR", name: "United Kingdom", lat: 54.3, lng: -2.95, continent: "Europe",
      climate: {
        codes: "OOOOIIIIIOOO",
        extra: ["", "", "", "", "", "", "", "", "", "", "", ""],
        note: "Mild, wet year-round; best May-September for driest weather.",
      },
      complexity: {
        visa: { level: "easy", label: "No visa, post-Brexit passport checks", detail: "EU/Belgian citizens do not need a visa for tourism (up to 6 months), but since Brexit are treated as third-country nationals: passports are stamped, and from 2025 the UK is rolling out an ETA (Electronic Travel Authorisation) requirement for most non-visa-national visitors, which must be obtained in advance online." },
        particular: { level: "moderate", label: "Customs declaration, ferry/Chunnel booking", detail: "As a foreign-registered (Belgian) vehicle, since Brexit you cross an actual customs/immigration border via ferry (Dover-Calais etc.) or Eurotunnel; carry vehicle registration, insurance (green card recommended), and be prepared for customs questions about goods carried, especially food/plant products which face EU-UK restrictions both ways." },
        stayLength: { level: "easy", label: "Up to 6 months", detail: "Standard visitor stay allowance for EU citizens is up to 6 months as a visitor, non-extendable for tourism purposes." },
        extendStay: { level: "hard", label: "Not possible as a visitor", detail: "Visitor visas/permissions generally cannot be extended from within the UK; you must leave and can re-enter afresh (subject to not appearing to live there)." },
        carnet: { level: "easy", label: "Not required", detail: "No Carnet de Passage needed for an EU-registered vehicle; standard temporary import rules apply, documented via ferry/Eurotunnel customs procedures." },
        vehicleStay: { level: "moderate", label: "6 months, temporary import rules", detail: "A foreign-registered vehicle may generally remain up to 6 months in a 12-month period under temporary admission rules; must not be sold, hired out, or used for local commercial purposes." },
        extendVeh: { level: "hard", label: "Difficult, must re-import", detail: "Extending beyond the 6-month temporary admission is not straightforward; typically requires the vehicle to leave and re-enter." },
        modernVeh: { level: "easy", label: "Excellent, full dealer network, drive on left", detail: "Full Mercedes-Benz dealer/service network and good fuel quality; remember the UK drives on the left, requiring extra care with a left-hand-drive Sprinter (mirrors, overtaking visibility)." },
        roadQuality: { level: "easy", label: "Good, congestion in cities", detail: "Motorways and main roads are well-maintained; be aware of low bridges/narrow lanes in rural areas and significant urban congestion/ULEZ zones (a Euro6 Sprinter qualifies for ULEZ)." },
      },
    },
  ];
  window.COUNTRY_DATA = window.COUNTRY_DATA || [];
  window.COUNTRY_DATA.push(...EUROPE_COUNTRIES);
})();
