// Country/region data for North America.
// Alphabetically ordered by name. Each entry:
//   id   - unique unit id (matches the map's country iso3 code, or iso3_region for
//          countries split into multiple climate regions)
//   iso  - ISO 3166-1 alpha-3 code used to match the map's GeoJSON country outlines
//   name - display name shown in the table and on the map
//   lat/lng - marker position on the map
//   climate - { codes, extra, note } or null if not yet researched
//     codes: 12-character string (JAN..DEC), one of V(avoid) / O(ok) / I(ideal)
//     extra: 12-entry array, each entry a combination of icon codes for that month
//            (or ""): H = extreme heat, C = extreme cold, R = extreme rain/monsoon,
//            T = overrun with tourists (only used where this is a genuine concern)
//     note: short free-text shown in a popup when clicking the country name
//   complexity - object with 9 fields (visa, particular, stayLength, extendStay,
//     carnet, vehicleStay, extendVeh, modernVeh, roadQuality), or null if not yet
//     researched. Each field: { level: "easy"|"moderate"|"hard", label, detail }
//   See /llm_update_instructions.md for the research prompt used to fill these in.
(function() {
  const NORTH_AMERICA_COUNTRIES = [
    { id: "BLZ", iso: "BLZ", name: "Belize", lat: 17.19, lng: -88.67, continent: "North America",
      climate: {
        codes: "IIIOOVVVVOOI",
        extra: ["", "", "", "", "", "HR", "HR", "HR", "HR", "R", "", ""],
        note: "Best Dec-April (dry season); June-Nov is hot, humid and hurricane season with heavy rain.",
      },
      complexity: {
        visa: { level: "easy", label: "Visa-free 30-90 days", detail: "Belgian/EU passport holders get a free entry stamp on arrival, typically 30 days, extendable." },
        particular: { level: "easy", label: "No special permits", detail: "No mandatory guide or special permit requirements; standard vehicle insurance is required at the border." },
        stayLength: { level: "easy", label: "30 days on arrival", detail: "Immigration typically grants 30 days; longer stays are possible for cruisers/overlanders who ask." },
        extendStay: { level: "easy", label: "Simple monthly extensions", detail: "Extensions are done at the Immigration Department in Belmopan or Belize City for a small fee, up to 6 months total." },
        carnet: { level: "easy", label: "No carnet, simple TIP", detail: "Belize does not require a Carnet de Passage; a Temporary Import Permit (TIP) for the vehicle is issued free at the border." },
        vehicleStay: { level: "easy", label: "Matches visa length", detail: "The TIP is usually issued for 30 days, matching the tourist stay, and can be renewed alongside stay extensions." },
        extendVeh: { level: "easy", label: "Renewed with stay", detail: "Vehicle permit extensions are handled at the same immigration/customs office as personal stay extensions." },
        modernVeh: { level: "moderate", label: "No Mercedes dealer", detail: "Diesel is available in towns but quality varies; there is no official Mercedes dealer in Belize, nearest full service is in Mexico or Guatemala." },
        roadQuality: { level: "moderate", label: "Good main roads, rough side roads", detail: "The Northern and Western Highways are paved and decent; rural and jungle roads can flood or wash out in the wet season (June-Nov)." },
      },
    },
    { id: "CAN_central", iso: "CAN", name: "Canada – Central", lat: 52, lng: -106, continent: "North America",
      climate: {
        codes: "VVVOOIIIOOVV",
        extra: ["C", "C", "", "", "", "", "H", "H", "", "", "C", "C"],
        note: "Short warm summer (June-Aug) is ideal for travel; brutally cold winters (Nov-March) make overlanding impractical.",
      },
      complexity: {
        visa: { level: "easy", label: "Visa-free eTA required", detail: "Belgian/EU citizens don't need a visa but must obtain a low-cost eTA (Electronic Travel Authorization) online before flying in; land border crossings from the US don't require the eTA but do require a valid passport." },
        particular: { level: "easy", label: "Standard entry rules", detail: "No special permits for the Prairie provinces; mandatory liability insurance and proof of vehicle ownership/registration required at the border." },
        stayLength: { level: "easy", label: "Up to 6 months", detail: "Visitors are typically admitted for up to 6 months at the discretion of the border officer." },
        extendStay: { level: "moderate", label: "Extension via IRCC online", detail: "Extensions ('visitor record') can be applied for online through IRCC before the current stay expires, processing can take weeks." },
        carnet: { level: "easy", label: "No carnet needed", detail: "Canada does not require a Carnet de Passage for temporary vehicle import by tourists; a temporary import is handled informally at the border with proof of ownership and insurance." },
        vehicleStay: { level: "easy", label: "Up to 12 months", detail: "A foreign-registered vehicle can generally remain in Canada temporarily for up to 12 months without formal importation, provided it's not sold or left permanently." },
        extendVeh: { level: "moderate", label: "Exit/re-entry usually simplest", detail: "There's no formal extension process; most overlanders simply exit and re-enter (e.g. via the US) to reset the clock." },
        modernVeh: { level: "easy", label: "Excellent Mercedes/diesel support", detail: "Ultra low sulfur diesel is standard and widely available; Mercedes-Benz has a strong dealer network in Regina, Saskatoon, Winnipeg and Calgary." },
        roadQuality: { level: "easy", label: "Excellent paved highways", detail: "The Trans-Canada Highway and provincial roads are well maintained; winter driving (ice, snow, whiteouts) is the main hazard outside summer season." },
      },
    },
    { id: "CAN_east", iso: "CAN", name: "Canada – East", lat: 46, lng: -71, continent: "North America",
      climate: {
        codes: "VVOOIIOOIOOV",
        extra: ["C", "C", "", "", "", "", "H", "H", "", "", "", "C"],
        note: "Best May-Oct with warm summers and stunning fall colors (Sept-Oct); winters are long, snowy and cold.",
      },
      complexity: {
        visa: { level: "easy", label: "Visa-free eTA required", detail: "Belgian/EU citizens don't need a visa but must obtain a low-cost eTA online before flying in; land crossings from the US only require a valid passport." },
        particular: { level: "easy", label: "Standard entry rules", detail: "Quebec's French-first signage aside, entry procedures are standard; mandatory liability insurance and proof of ownership needed at the border." },
        stayLength: { level: "easy", label: "Up to 6 months", detail: "Visitors are typically admitted for up to 6 months at the officer's discretion." },
        extendStay: { level: "moderate", label: "Extension via IRCC online", detail: "Extensions can be applied for online through IRCC before the current authorized stay expires; processing can take several weeks." },
        carnet: { level: "easy", label: "No carnet needed", detail: "No Carnet de Passage required for tourist vehicles; informal temporary import at the border with proof of ownership and insurance." },
        vehicleStay: { level: "easy", label: "Up to 12 months", detail: "A foreign vehicle can stay temporarily up to 12 months without formal importation, provided it isn't sold or left permanently." },
        extendVeh: { level: "moderate", label: "Exit/re-entry usually simplest", detail: "No formal extension mechanism; most overlanders exit to the US and re-enter to reset the clock." },
        modernVeh: { level: "easy", label: "Excellent Mercedes/diesel support", detail: "Ultra low sulfur diesel is standard; Mercedes-Benz has extensive dealer networks in Montreal, Quebec City, Ottawa and Toronto." },
        roadQuality: { level: "easy", label: "Excellent paved highways", detail: "Highway 401, the Trans-Canada and provincial routes are in good condition; winter ice/snow is the main seasonal hazard." },
      },
    },
    { id: "CAN_north", iso: "CAN", name: "Canada – North", lat: 65, lng: -100, continent: "North America",
      climate: {
        codes: "VVVVOOIIOVVV",
        extra: ["C", "C", "C", "C", "", "", "", "", "", "C", "C", "C"],
        note: "Only a brief window (late June-Aug) is truly accessible by road; extreme cold and limited daylight dominate the rest of the year.",
      },
      complexity: {
        visa: { level: "easy", label: "Visa-free eTA required", detail: "Same national rules apply: Belgian/EU citizens need a free eTA for air entry, none needed for land crossing from the south." },
        particular: { level: "moderate", label: "Remote, fuel/service gaps", detail: "Vast distances between fuel stops (e.g. Dempster Highway, Northwest Territories) require carrying extra fuel and supplies; no special permits needed for the road-accessible areas." },
        stayLength: { level: "easy", label: "Up to 6 months", detail: "Same national rule of up to 6 months applies as anywhere else in Canada." },
        extendStay: { level: "moderate", label: "Extension via IRCC online", detail: "Same national extension process (IRCC visitor record) applies; there are no immigration offices in the far north so file well ahead." },
        carnet: { level: "easy", label: "No carnet needed", detail: "No Carnet de Passage required; same informal temporary import process as the rest of Canada." },
        vehicleStay: { level: "easy", label: "Up to 12 months", detail: "Same 12-month temporary import allowance applies nationally." },
        extendVeh: { level: "moderate", label: "Exit/re-entry usually simplest", detail: "No formal in-country extension; practically irrelevant here since most visits are short due to climate and distances." },
        modernVeh: { level: "hard", label: "Sparse service, harsh conditions", detail: "Diesel is available at limited stations along the Dempster and Alaska Highways but at a premium; no Mercedes dealer network north of Whitehorse/Yellowknife, and extreme cold stresses modern diesel emissions systems (DEF freezing risk)." },
        roadQuality: { level: "hard", label: "Gravel, remote, seasonal", detail: "Roads like the Dempster and Ingraham Trail are unpaved gravel with sharp rocks (tire hazard); many routes are seasonal ice roads only passable in winter, others impassable in spring thaw." },
      },
    },
    { id: "CAN_west", iso: "CAN", name: "Canada – West", lat: 54, lng: -125, continent: "North America",
      climate: {
        codes: "VVOOIIIOOOVV",
        extra: ["C", "C", "", "", "", "", "H", "", "", "", "", "C"],
        note: "Best May-Sept, especially the Rockies and BC coast; mountain passes can close with early/late snow outside this window.",
      },
      complexity: {
        visa: { level: "easy", label: "Visa-free eTA required", detail: "Belgian/EU citizens need a free eTA for air arrival; land crossings from the US only require a valid passport." },
        particular: { level: "easy", label: "Standard entry rules", detail: "No special permits for BC/Alberta; mandatory liability insurance and ownership proof required at the border." },
        stayLength: { level: "easy", label: "Up to 6 months", detail: "Visitors typically admitted for up to 6 months at the border officer's discretion." },
        extendStay: { level: "moderate", label: "Extension via IRCC online", detail: "Extensions handled online via IRCC before the authorized stay expires; processing can take several weeks." },
        carnet: { level: "easy", label: "No carnet needed", detail: "No Carnet de Passage required; informal temporary vehicle import at the border with proof of ownership and insurance." },
        vehicleStay: { level: "easy", label: "Up to 12 months", detail: "Foreign vehicles can remain temporarily up to 12 months without formal importation." },
        extendVeh: { level: "moderate", label: "Exit/re-entry usually simplest", detail: "No formal extension mechanism; overlanders typically exit to the US and re-enter." },
        modernVeh: { level: "easy", label: "Excellent Mercedes/diesel support", detail: "Ultra low sulfur diesel widely available; Mercedes-Benz dealers in Vancouver, Calgary, Edmonton and Kelowna." },
        roadQuality: { level: "moderate", label: "Good roads, mountain closures", detail: "Highways are well maintained but Rocky Mountain passes (e.g. Highway 1, Coquihalla) can close temporarily for snow/avalanche control even in shoulder season." },
      },
    },
    { id: "CRI", iso: "CRI", name: "Costa Rica", lat: 9.72, lng: -84.24, continent: "North America",
      climate: {
        codes: "IIIIOVVVVVOI",
        extra: ["", "", "T", "T", "R", "R", "R", "R", "R", "R", "", ""],
        note: "Dry season (Dec-April) is ideal but peak parks (Manuel Antonio, Monteverde) get crowded; green/rainy season (May-Nov) brings frequent heavy afternoon downpours.",
      },
      complexity: {
        visa: { level: "easy", label: "Visa-free 90 days", detail: "Belgian/EU passport holders get a free 90-day tourist stamp on arrival, no visa needed." },
        particular: { level: "easy", label: "Mandatory insurance at border", detail: "Costa Rica requires proof of mandatory liability insurance (available for purchase at the border, INS) for foreign vehicles; no guide requirement." },
        stayLength: { level: "easy", label: "90 days on arrival", detail: "Standard tourist entry is 90 days, non-extendable from within without leaving the country." },
        extendStay: { level: "moderate", label: "Border run required", detail: "There's no simple in-country extension; most travelers do a short border run to Nicaragua or Panama to reset the 90 days." },
        carnet: { level: "easy", label: "No carnet, simple TIP", detail: "Costa Rica does not require a Carnet de Passage; a free Temporary Import Permit (TIP) for the vehicle is issued at customs on arrival." },
        vehicleStay: { level: "moderate", label: "90 days, strictly enforced", detail: "The vehicle TIP matches the 90-day tourist stay and is tracked in a computer system; overstaying triggers fines/import taxes." },
        extendVeh: { level: "hard", label: "Must exit to renew", detail: "The vehicle permit cannot be renewed from inside the country; you must physically leave with the vehicle to reset it, similar to the personal visa." },
        modernVeh: { level: "moderate", label: "Diesel ok, limited AWD parts", detail: "Diesel is available and reasonable quality; Mercedes-Benz has a dealer in San José but Sprinter 4x4/AWD specific parts may need importing." },
        roadQuality: { level: "moderate", label: "Good main roads, rough rural", detail: "Highways like the Interamericana are decent; rural and coastal roads can be potholed and flood-prone in rainy season (May-Nov), some river crossings require care." },
      },
    },
    { id: "SLV", iso: "SLV", name: "El Salvador", lat: 13.79, lng: -88.91, continent: "North America",
      climate: {
        codes: "IIOOOVVVVVOI",
        extra: ["", "", "", "H", "", "R", "R", "R", "R", "R", "", ""],
        note: "Best Nov-March (dry, cooler); rainy season May-Oct brings frequent heavy tropical downpours and hot, humid conditions.",
      },
      complexity: {
        visa: { level: "easy", label: "Visa-free via CA-4", detail: "Belgian/EU passport holders enter visa-free; El Salvador is part of the CA-4 agreement with Guatemala, Honduras and Nicaragua sharing a common 90-day tourist permit." },
        particular: { level: "easy", label: "No special permits", detail: "No mandatory guide or special permits; standard vehicle insurance recommended though not always checked at the border." },
        stayLength: { level: "easy", label: "90 days (CA-4 zone)", detail: "The 90 days is shared across the whole CA-4 bloc (Guatemala, Honduras, El Salvador, Nicaragua combined), not reset by crossing between them." },
        extendStay: { level: "moderate", label: "Extension via Migración", detail: "Extensions can be requested at the immigration office in San Salvador, but many overlanders instead exit to Costa Rica or Mexico to reset the CA-4 clock." },
        carnet: { level: "easy", label: "No carnet, simple TIP", detail: "No Carnet de Passage required; a free Temporary Import Permit is issued at the border, valid for the CA-4 region." },
        vehicleStay: { level: "moderate", label: "Tied to CA-4 90 days", detail: "The vehicle permit follows the same shared 90-day CA-4 rule as the personal visa." },
        extendVeh: { level: "moderate", label: "Exit CA-4 zone to renew", detail: "Practically easiest to exit the whole CA-4 bloc (e.g. to Costa Rica) to reset both personal and vehicle permits." },
        modernVeh: { level: "moderate", label: "Diesel ok, no Mercedes dealer", detail: "Diesel is available and reasonable; no official Mercedes-Benz dealer in El Salvador, nearest full support is in Guatemala City." },
        roadQuality: { level: "moderate", label: "Decent highways, rough backroads", detail: "Main highways (Pan-American, coastal) are well paved; rural roads can be steep, potholed, or washed out in the rainy season." },
      },
    },
    { id: "GTM", iso: "GTM", name: "Guatemala", lat: 15.78, lng: -90.23, continent: "North America",
      climate: {
        codes: "IIOOOVVVVVOI",
        extra: ["", "", "", "", "", "R", "R", "R", "R", "R", "", ""],
        note: "Best Nov-April (dry season); rainy season May-Oct brings heavy afternoon storms and landslide risk in the highlands.",
      },
      complexity: {
        visa: { level: "easy", label: "Visa-free via CA-4", detail: "Belgian/EU passport holders enter visa-free under the CA-4 agreement, sharing a common 90-day permit with Honduras, El Salvador and Nicaragua." },
        particular: { level: "easy", label: "No special permits", detail: "No mandatory guide requirement; standard vehicle insurance recommended. Some highland areas have petty theft/security concerns, so route planning matters more than paperwork." },
        stayLength: { level: "easy", label: "90 days (CA-4 zone)", detail: "The 90-day allowance is shared across the whole CA-4 bloc and is not reset simply by crossing internal CA-4 borders." },
        extendStay: { level: "moderate", label: "Extension via Migración", detail: "Extensions can be requested at immigration offices in Guatemala City, but exiting the whole CA-4 zone (e.g. to Belize or Mexico) is the more common reset method." },
        carnet: { level: "easy", label: "No carnet, simple TIP", detail: "No Carnet de Passage required; a free Temporary Import Permit is issued at the border for the vehicle, valid across the CA-4 region." },
        vehicleStay: { level: "moderate", label: "Tied to CA-4 90 days", detail: "The vehicle TIP follows the same shared 90-day CA-4 rule as the tourist stamp." },
        extendVeh: { level: "moderate", label: "Exit CA-4 zone to renew", detail: "Best reset by exiting the whole CA-4 bloc, e.g. crossing into Mexico or Belize, then re-entering." },
        modernVeh: { level: "moderate", label: "Mercedes dealer in capital", detail: "Diesel quality is generally acceptable; Guatemala City has an official Mercedes-Benz dealer, the best-supported option in Central America north of Panama." },
        roadQuality: { level: "moderate", label: "Good highways, steep backroads", detail: "The Pan-American Highway (CA-1) is well maintained; secondary roads in the highlands are steep, winding and prone to landslides in the rainy season." },
      },
    },
    { id: "HND", iso: "HND", name: "Honduras", lat: 14.5, lng: -86.25, continent: "North America",
      climate: {
        codes: "IIOOOVVVVVOI",
        extra: ["", "", "", "", "", "R", "R", "R", "R", "R", "", ""],
        note: "Best Nov-April (dry season); rainy season May-Oct brings heavy downpours and occasional flooding, especially on the Caribbean coast.",
      },
      complexity: {
        visa: { level: "easy", label: "Visa-free via CA-4", detail: "Belgian/EU passport holders enter visa-free under the CA-4 agreement, sharing a common 90-day permit with Guatemala, El Salvador and Nicaragua." },
        particular: { level: "moderate", label: "Security awareness advised", detail: "No mandatory guide or permits, but some regions (parts of the north coast, certain urban areas) have higher crime rates; route and overnight-spot planning matters." },
        stayLength: { level: "easy", label: "90 days (CA-4 zone)", detail: "The 90 days is shared across the CA-4 bloc and not reset by moving between its member countries." },
        extendStay: { level: "moderate", label: "Extension via Migración", detail: "Extensions can be requested at immigration in Tegucigalpa or San Pedro Sula; most overlanders instead exit the whole CA-4 zone to reset the clock." },
        carnet: { level: "easy", label: "No carnet, simple TIP", detail: "No Carnet de Passage required; a free Temporary Import Permit is issued at the border, valid across the CA-4 zone." },
        vehicleStay: { level: "moderate", label: "Tied to CA-4 90 days", detail: "The vehicle TIP follows the same shared 90-day CA-4 rule as the personal visa." },
        extendVeh: { level: "moderate", label: "Exit CA-4 zone to renew", detail: "Best reset by exiting the whole CA-4 bloc (e.g. to Costa Rica or Mexico) and re-entering." },
        modernVeh: { level: "hard", label: "Limited dealer support", detail: "Diesel is available but quality can be inconsistent outside major cities; no dedicated Mercedes-Benz dealer, nearest full support is Guatemala City." },
        roadQuality: { level: "moderate", label: "Mixed quality, weather-dependent", detail: "Main highways are reasonable; secondary and coastal roads can flood or wash out during the rainy season, and some mountain routes are rough." },
      },
    },
    { id: "MEX", iso: "MEX", name: "Mexico", lat: 23.63, lng: -101.97, continent: "North America",
      climate: {
        codes: "IIIOOVVVVVOI",
        extra: ["", "", "", "H", "H", "R", "R", "R", "R", "R", "", ""],
        note: "Best Nov-March (dry, mild); central/southern regions get hot and humid with heavy rain May-Oct, hurricane season affects both coasts June-Nov.",
      },
      complexity: {
        visa: { level: "easy", label: "Visa-free 180 days", detail: "Belgian/EU passport holders receive a free tourist card (FMM) on arrival, valid up to 180 days." },
        particular: { level: "moderate", label: "TIP required beyond border zone", detail: "Travel beyond the ~20-30km border free zone (and outside Baja California/Sonora free zone) requires a Temporary Vehicle Import Permit (TIP), obtained online via Banjercito or at the border with a refundable deposit." },
        stayLength: { level: "easy", label: "Up to 180 days", detail: "The FMM tourist card is typically issued for up to 180 days, among the most generous in the region." },
        extendStay: { level: "hard", label: "No in-country extension", detail: "Mexico generally does not allow extending the FMM from within the country; travelers must exit and re-enter to get a fresh stamp." },
        carnet: { level: "easy", label: "No carnet, online TIP instead", detail: "Mexico does not require a Carnet de Passage; the Banjercito TIP system (with refundable bond, ~$200-400+ depending on vehicle age) handles temporary vehicle import." },
        vehicleStay: { level: "moderate", label: "Up to 180 days, deposit-based", detail: "The TIP is generally valid up to 180 days and requires a credit-card deposit/bond that's refunded on exit; failing to cancel it can cause issues on future entries." },
        extendVeh: { level: "hard", label: "Must exit to renew", detail: "Like the personal visa, the vehicle TIP cannot be extended in-country; exiting and re-entering is required for both simultaneously." },
        modernVeh: { level: "moderate", label: "Good in cities, patchy rural diesel", detail: "Mercedes-Benz has a strong dealer network in major cities (Mexico City, Guadalajara, Monterrey); diesel quality is generally fine at Pemex/major brands but can be less reliable at remote rural stations." },
        roadQuality: { level: "moderate", label: "Good toll roads, variable free roads", detail: "Toll highways (cuota) are excellent; free roads (libre) vary widely in quality, and mountain routes can have landslide/fog hazards; hurricane season affects coastal roads June-Nov." },
      },
    },
    { id: "NIC", iso: "NIC", name: "Nicaragua", lat: 12.87, lng: -85.41, continent: "North America",
      climate: {
        codes: "IIOOOVVVVVOI",
        extra: ["", "", "", "H", "", "R", "R", "R", "R", "R", "", ""],
        note: "Best Nov-April (dry season); rainy season May-Oct brings frequent heavy downpours, especially on the Caribbean side.",
      },
      complexity: {
        visa: { level: "easy", label: "Visa-free via CA-4", detail: "Belgian/EU passport holders enter visa-free under the CA-4 agreement, sharing a common 90-day tourist permit with Guatemala, Honduras and El Salvador." },
        particular: { level: "moderate", label: "Political situation shifting", detail: "No mandatory guide or special permits, but Nicaragua's political/security climate has been more unpredictable in recent years; check current travel advisories before crossing." },
        stayLength: { level: "easy", label: "90 days (CA-4 zone)", detail: "The 90-day stay is shared across the CA-4 bloc and not reset by moving between member countries internally." },
        extendStay: { level: "moderate", label: "Extension via Migración", detail: "Extensions can be requested at immigration in Managua; most overlanders instead exit the whole CA-4 zone (e.g. to Costa Rica) to reset the clock." },
        carnet: { level: "easy", label: "No carnet, simple TIP", detail: "No Carnet de Passage required; a Temporary Import Permit is issued at the border (small fee), valid across the CA-4 zone." },
        vehicleStay: { level: "moderate", label: "Tied to CA-4 90 days", detail: "The vehicle TIP follows the same shared 90-day CA-4 rule as the personal visa." },
        extendVeh: { level: "moderate", label: "Exit CA-4 zone to renew", detail: "Best reset by exiting the whole CA-4 bloc, most commonly crossing into Costa Rica." },
        modernVeh: { level: "hard", label: "No Mercedes dealer", detail: "Diesel is available but quality can be inconsistent outside Managua; no official Mercedes-Benz dealer, nearest full service is Costa Rica or Guatemala." },
        roadQuality: { level: "moderate", label: "Decent main routes, rough rural", detail: "The Pan-American Highway is generally in good condition; rural and lakeside roads can be rough and flood-prone in the wet season." },
      },
    },
    { id: "PAN", iso: "PAN", name: "Panama", lat: 8.42, lng: -80.1, continent: "North America",
      climate: {
        codes: "IIOOOVVVVVOI",
        extra: ["", "", "", "", "", "R", "R", "R", "R", "R", "", ""],
        note: "Best mid-Dec to mid-April (dry season); rainy season May-Nov brings frequent heavy downpours and higher humidity year-round.",
      },
      complexity: {
        visa: { level: "easy", label: "Visa-free 90-180 days", detail: "Belgian/EU passport holders enter visa-free, typically granted 90 days on arrival (sometimes up to 180 at officer discretion)." },
        particular: { level: "hard", label: "Darién Gap has no road", detail: "There is no road connection to Colombia through the Darién Gap; vehicles must be shipped by container/RoRo (from Colón) or occasionally barge to continue into South America. Plan and book weeks in advance." },
        stayLength: { level: "easy", label: "90-180 days on arrival", detail: "Tourist entry is usually 90 days, though some nationalities/entries get up to 180; check the stamp given." },
        extendStay: { level: "moderate", label: "Extension via Migración", detail: "Extensions ('prórroga de turista') can be requested at the National Immigration Service in Panama City, generally straightforward but requires paperwork and a fee." },
        carnet: { level: "easy", label: "No carnet, simple TIP", detail: "No Carnet de Passage required for road entry from Costa Rica; a free Temporary Import Permit is issued at the border, valid up to 90 days (renewable)." },
        vehicleStay: { level: "moderate", label: "90 days, renewable", detail: "The vehicle TIP is typically valid for 90 days and can be renewed once at customs (Aduanas) in Panama City before shipping onward or exiting." },
        extendVeh: { level: "moderate", label: "One renewal, then must ship/exit", detail: "After the permitted renewal, the vehicle must either be shipped onward (Darién Gap) or exit back into Central America." },
        modernVeh: { level: "easy", label: "Best-supported in region", detail: "Panama City has full Mercedes-Benz dealer support and good diesel quality, arguably the best service point in the region before/after shipping across the Darién Gap." },
        roadQuality: { level: "moderate", label: "Good highways, jungle backroads rough", detail: "The Pan-American Highway is well paved to Yaviza; roads become progressively rougher toward the Darién province, and rainy season increases flooding/landslide risk." },
      },
    },
    { id: "USA_alaska", iso: "USA", name: "USA – Alaska", lat: 64, lng: -153, continent: "North America",
      climate: {
        codes: "VVVVOIIIOVVV",
        extra: ["C", "C", "C", "", "", "", "", "", "", "", "C", "C"],
        note: "Short window (May-Sept) for road access via the Alaska Highway; long, dark, extremely cold winters make overlanding impractical outside summer.",
      },
      complexity: {
        visa: { level: "moderate", label: "ESTA/visa waiver", detail: "Belgian/EU citizens use the Visa Waiver Program (ESTA) for stays up to 90 days; must apply online before travel, and it's tied to arrival by air/sea (land entry from Canada follows the same 90-day rule under ESTA)." },
        particular: { level: "hard", label: "Vehicle import rules complex", detail: "A foreign (non-US-spec) camper van faces EPA/DOT rules: vehicles under 25 years old generally cannot be permanently imported without EPA/DOT compliance, but temporary importation for personal use up to 1 year is permitted under a CBP bond, and can sometimes be extended once." },
        stayLength: { level: "moderate", label: "Up to 90 days (ESTA)", detail: "ESTA visa waiver stays are capped at 90 days and generally cannot be extended; a B2 visitor visa (longer process) allows longer stays if needed." },
        extendStay: { level: "hard", label: "ESTA not extendable", detail: "Overstaying or extending under ESTA is not permitted; must exit before the 90 days lapse or apply for a different visa category in advance." },
        carnet: { level: "moderate", label: "No carnet, CBP temporary import", detail: "The US does not use the international Carnet de Passage system; instead temporary import is handled by US Customs and Border Protection (CBP) at entry, tied to your personal stay/bond." },
        vehicleStay: { level: "moderate", label: "Up to 1 year, bonded", detail: "Non-conforming foreign vehicles can be temporarily imported for personal use for up to 1 year under a CBP/EPA/DOT exemption, generally requiring a bond." },
        extendVeh: { level: "hard", label: "One extension possible, then must exit", detail: "A single extension may be possible with CBP/EPA approval, but ultimately the vehicle must leave the US (e.g. back to Canada) before the deadline." },
        modernVeh: { level: "moderate", label: "Remote, limited but functional", detail: "Diesel is available along the Alaska Highway/main routes but stations are sparse; no Mercedes-Benz dealer in Alaska itself, nearest full service is in the Lower 48 or western Canada." },
        roadQuality: { level: "moderate", label: "Good main roads, harsh remote routes", detail: "The Alaska Highway and Seward/Parks Highways are paved and well maintained in summer; remote gravel roads (Dalton Highway) are rough with limited services and require preparation." },
      },
    },
    { id: "USA_central", iso: "USA", name: "USA – Central", lat: 40, lng: -98, continent: "North America",
      climate: {
        codes: "VVOOIIOOIOOV",
        extra: ["C", "C", "", "", "", "H", "H", "H", "", "", "", "C"],
        note: "Best April-June and Sept-Oct; summers can be extremely hot and humid, winters bring severe cold and occasional blizzards on the Plains.",
      },
      complexity: {
        visa: { level: "moderate", label: "ESTA/visa waiver", detail: "Belgian/EU citizens use ESTA for stays up to 90 days without a visa; must apply online in advance and it's linked to specific arrival requirements." },
        particular: { level: "hard", label: "Vehicle import rules complex", detail: "Same as elsewhere in the US: a foreign-registered camper van under 25 years old cannot be permanently imported without full EPA/DOT compliance, but temporary import for personal use up to 1 year is allowed under a CBP bond." },
        stayLength: { level: "moderate", label: "Up to 90 days (ESTA)", detail: "ESTA visa waiver entries are capped at 90 days; longer visits require a B2 visitor visa applied for in advance." },
        extendStay: { level: "hard", label: "ESTA not extendable", detail: "No extension is possible under ESTA; must exit before the 90 days expire." },
        carnet: { level: "moderate", label: "No carnet, CBP temporary import", detail: "The US doesn't use Carnet de Passage; CBP handles temporary vehicle import at the port of entry instead." },
        vehicleStay: { level: "moderate", label: "Up to 1 year, bonded", detail: "Temporary import for personal use is permitted up to 1 year under a CBP/EPA/DOT exemption, typically with a bond requirement." },
        extendVeh: { level: "hard", label: "Limited extension, then must exit", detail: "A single extension may sometimes be granted, but the vehicle ultimately must leave the country (e.g. to Canada or Mexico)." },
        modernVeh: { level: "easy", label: "Excellent Mercedes/diesel support", detail: "Ultra low sulfur diesel is standard and widely available at truck stops; Mercedes-Benz Sprinter dealer network is dense across major Central US cities (Dallas, Denver, Kansas City, Chicago)." },
        roadQuality: { level: "easy", label: "Excellent interstate network", detail: "Interstates and major highways are excellent; watch for severe weather (tornadoes in spring, blizzards/ice storms in winter, especially Tornado Alley states)." },
      },
    },
    { id: "USA_east", iso: "USA", name: "USA – East", lat: 38, lng: -82, continent: "North America",
      climate: {
        codes: "VOOOIVVOOOOV",
        extra: ["C", "", "", "", "", "HT", "HT", "T", "", "", "", "C"],
        note: "Best April-June and Sept-Oct; National Parks and coastal areas get crowded and hot/humid in summer (June-Aug), winters bring cold and occasional snow especially in the north.",
      },
      complexity: {
        visa: { level: "moderate", label: "ESTA/visa waiver", detail: "Belgian/EU citizens use ESTA for stays up to 90 days without a visa, applied for online in advance." },
        particular: { level: "hard", label: "Vehicle import rules complex", detail: "Same national rule: a foreign camper van under 25 years old generally cannot be permanently imported without EPA/DOT compliance, but temporary import for personal use is allowed up to 1 year under CBP bond." },
        stayLength: { level: "moderate", label: "Up to 90 days (ESTA)", detail: "ESTA entries are capped at 90 days; longer stays require applying for a B2 visitor visa in advance." },
        extendStay: { level: "hard", label: "ESTA not extendable", detail: "No extension possible under ESTA; must exit before the 90-day period lapses." },
        carnet: { level: "moderate", label: "No carnet, CBP temporary import", detail: "No Carnet de Passage system used; CBP manages temporary vehicle import at the point of entry." },
        vehicleStay: { level: "moderate", label: "Up to 1 year, bonded", detail: "Temporary import for personal use is permitted up to 1 year under a CBP/EPA/DOT exemption, usually with a bond." },
        extendVeh: { level: "hard", label: "Limited extension, then must exit", detail: "A single extension may be possible, but the vehicle must ultimately leave the country." },
        modernVeh: { level: "easy", label: "Excellent Mercedes/diesel support", detail: "Ultra low sulfur diesel widely available; dense Mercedes-Benz Sprinter dealer network throughout the East Coast (NYC, DC, Atlanta, Boston)." },
        roadQuality: { level: "easy", label: "Excellent interstates, seasonal storms", detail: "Interstate and state highway quality is excellent; hurricane season (June-Nov) affects the southeast/coastal areas, winter storms/ice affect the north." },
      },
    },
    { id: "USA_west", iso: "USA", name: "USA – West", lat: 40, lng: -116, continent: "North America",
      climate: {
        codes: "VOOOIVVVOOOV",
        extra: ["C", "", "", "", "", "HT", "HT", "HT", "T", "", "", "C"],
        note: "Best April-June and Sept-Oct; National Parks (Yellowstone, Grand Canyon, Zion) get very crowded June-Sept and desert areas get dangerously hot, winters bring heavy snow in the Rockies/Sierra.",
      },
      complexity: {
        visa: { level: "moderate", label: "ESTA/visa waiver", detail: "Belgian/EU citizens use ESTA for stays up to 90 days without a visa, applied for online in advance." },
        particular: { level: "hard", label: "Vehicle import rules complex", detail: "Same national rule: foreign camper vans under 25 years old cannot be permanently imported without EPA/DOT compliance, but temporary import for personal use up to 1 year is allowed under a CBP bond." },
        stayLength: { level: "moderate", label: "Up to 90 days (ESTA)", detail: "ESTA entries are capped at 90 days; longer visits require a B2 visitor visa applied for in advance." },
        extendStay: { level: "hard", label: "ESTA not extendable", detail: "No extension possible under ESTA; must exit before the 90 days expire." },
        carnet: { level: "moderate", label: "No carnet, CBP temporary import", detail: "No Carnet de Passage used; CBP manages temporary vehicle import at the port of entry." },
        vehicleStay: { level: "moderate", label: "Up to 1 year, bonded", detail: "Temporary import for personal use is permitted up to 1 year under a CBP/EPA/DOT exemption, typically requiring a bond." },
        extendVeh: { level: "hard", label: "Limited extension, then must exit", detail: "A single extension may sometimes be possible, but the vehicle ultimately must leave the country (e.g. to Canada or Mexico)." },
        modernVeh: { level: "easy", label: "Excellent Mercedes/diesel support", detail: "Ultra low sulfur diesel widely available even in remote areas; Mercedes-Benz Sprinter dealer network covers major western cities (LA, Denver, Seattle, Phoenix)." },
        roadQuality: { level: "moderate", label: "Excellent highways, mountain/desert hazards", detail: "Interstates and highways are excellent; mountain passes (Sierra Nevada, Rockies) can close with early/late snow, and desert routes require heat/water precautions in summer." },
      },
    },
  ];
  window.COUNTRY_DATA = window.COUNTRY_DATA || [];
  window.COUNTRY_DATA.push(...NORTH_AMERICA_COUNTRIES);
})();
