// Country/region data for South America.
// Alphabetically ordered by name. Each entry:
//   id   - unique unit id (matches the map's country iso3 code, or iso3_region for
//          countries split into multiple climate regions)
//   iso  - ISO 3166-1 alpha-3 code used to match the map's GeoJSON country outlines
//   name - display name shown in the table and on the map
//   lat/lng - marker position on the map
//   climate - { codes, extra, note } or null if not yet researched
//     codes: 12-character string (JAN..DEC), one of V(avoid) / O(ok) / I(ideal)
//     extra: 12-entry array, each entry a combination of icon codes for that month
//            (or ""): H = extreme heat, C = extreme cold, R = extreme rain/monsoon,
//            T = overrun with tourists (only used where this is a genuine concern)
//     note: short free-text shown in a popup when clicking the country name
//   complexity - object with 9 fields (visa, particular, stayLength, extendStay,
//     carnet, vehicleStay, extendVeh, modernVeh, roadQuality), or null if not yet
//     researched. Each field: { level: "easy"|"moderate"|"hard", label, detail }
//   See /llm_update_instructions.md for the research prompt used to fill these in.
(function() {
  const SOUTH_AMERICA_COUNTRIES = [
    { id: "ARG_north", iso: "ARG", name: "Argentina – North", lat: -27, lng: -64, continent: "South America",
      climate: {
        codes: "VVOIIOOOOOIV",
        extra: ["H", "H", "", "", "", "", "", "", "", "", "", "H"],
        note: "Subtropical north (Salta, Iguazú, Chaco) is hot and humid Dec-Feb; best travel is the dry, mild Apr-Sept window.",
      },
      complexity: {
        visa: { level: "easy", label: "Visa-free entry", detail: "Belgian/EU passport holders enter visa-free for up to 90 days as tourists; stamped on arrival at any official border or airport." },
        particular: { level: "easy", label: "No special permits", detail: "No mandatory guide or special permits for the northern regions; standard vehicle insurance (seguro) is required and best bought locally at the border." },
        stayLength: { level: "easy", label: "90 days on entry", detail: "Standard tourist entry stamp grants 90 days, renewable." },
        extendStay: { level: "easy", label: "Border run or Migraciones", detail: "Extend by leaving and re-entering (e.g. via Bolivia/Paraguay/Chile) or applying at a Migraciones office in a provincial capital; both are routine." },
        carnet: { level: "moderate", label: "Not required but useful", detail: "Argentina does not officially require a Carnet de Passage for tourist vehicles; a Temporary Import Permit (TIP) is issued free at the border instead, though a carnet can smooth things at some crossings." },
        vehicleStay: { level: "easy", label: "TIP matches visa, 90 days", detail: "The free TIP is normally issued for the same 90 days as the personal visa and stamped in your passport." },
        extendVeh: { level: "moderate", label: "Extend with Aduana", detail: "Vehicle TIP extension requires a visit to the customs office (Aduana), usually straightforward but requires some patience and Spanish." },
        modernVeh: { level: "easy", label: "Good diesel & service", detail: "Diesel is widely available and reasonably priced; Mercedes-Benz has an established dealer network in larger northern cities like Salta and Resistencia." },
        roadQuality: { level: "moderate", label: "Good main roads, some dirt", detail: "Major routes (RN9, RN34) are paved and well maintained; secondary roads into the Andean foothills and Chaco can be unpaved and dusty, occasionally flooded in summer storms." },
      },
    },
    { id: "ARG_patagonia", iso: "ARG", name: "Argentina – Patagonia", lat: -45, lng: -69, continent: "South America",
      climate: {
        codes: "IIOVVVVVVOII",
        extra: ["T", "T", "", "C", "C", "C", "C", "C", "C", "", "", "T"],
        note: "Best Nov-Mar (austral summer); winters (Jun-Aug) bring severe cold, snow, and many services/roads closed.",
      },
      complexity: {
        visa: { level: "easy", label: "Visa-free entry", detail: "Same national visa policy as the rest of Argentina: 90 days visa-free for Belgian/EU passport holders." },
        particular: { level: "easy", label: "No special permits", detail: "No mandatory guide requirements; some national parks (e.g. Los Glaciares, Torres del Paine on the Chilean side) charge entry fees but no special vehicle permits." },
        stayLength: { level: "easy", label: "90 days on entry", detail: "Standard tourist stamp of 90 days applies nationwide." },
        extendStay: { level: "easy", label: "Border run or Migraciones", detail: "Easy to extend via a border crossing into Chile and back, or at a regional Migraciones office in cities like Bariloche or Río Gallegos." },
        carnet: { level: "moderate", label: "Not required but useful", detail: "No official Carnet de Passage requirement; a free Temporary Import Permit is issued at the border, but frequent Chile-Argentina border crossing in Patagonia makes carrying a carnet convenient." },
        vehicleStay: { level: "easy", label: "TIP matches visa, 90 days", detail: "Vehicle TIP is issued for 90 days matching the tourist visa." },
        extendVeh: { level: "moderate", label: "Extend with Aduana", detail: "Extensions are handled at customs offices in regional hubs; process is routine but requires an in-person visit." },
        modernVeh: { level: "moderate", label: "Good in towns, sparse between", detail: "Diesel and workshops are reliable in towns like Bariloche, El Calafate and Río Gallegos, but distances between services can exceed 300km; carry spares." },
        roadQuality: { level: "moderate", label: "Ruta 40 mostly paved now", detail: "Ruta 40 is largely paved but remote stretches can still be gravel (ripio); strong Patagonian winds are a real hazard for high-sided vans, and winter snow closes some mountain passes." },
      },
    },
    { id: "BOL", iso: "BOL", name: "Bolivia", lat: -16.32, lng: -63.54, continent: "South America",
      climate: {
        codes: "VVOOIIIIOOOV",
        extra: ["R", "R", "", "", "C", "C", "C", "", "", "", "", "R"],
        note: "Dry season May-Oct is best, especially for the Altiplano/Uyuni; wet season Dec-Mar brings heavy rain and can close dirt roads, while high-altitude nights are cold year-round.",
      },
      complexity: {
        visa: { level: "easy", label: "Visa-free entry", detail: "Belgian/EU passport holders enter visa-free for up to 90 days per year as tourists." },
        particular: { level: "moderate", label: "Insurance & altitude", detail: "Third-party vehicle insurance (SOAT) is required and sold at the border; no mandatory guide, but high-altitude routes (Uyuni, Altiplano) demand acclimatization and self-sufficiency planning." },
        stayLength: { level: "easy", label: "90 days per year", detail: "Standard entry grants up to 90 days, cumulative within a calendar year." },
        extendStay: { level: "moderate", label: "Migración extensions", detail: "Extensions beyond the initial stamp are handled at Migración offices in major cities (La Paz, Santa Cruz); straightforward but requires paperwork and small fees." },
        carnet: { level: "moderate", label: "Carnet recommended", detail: "A Carnet de Passage is not universally enforced but strongly recommended; a free Temporary Import Permit is otherwise issued at the border." },
        vehicleStay: { level: "easy", label: "TIP typically 90 days", detail: "Vehicle TIP is usually issued matching the 90-day tourist stay." },
        extendVeh: { level: "moderate", label: "Aduana extension needed", detail: "Extending vehicle import requires a visit to Aduana Nacional offices; doable but bureaucratic and Spanish-language paperwork heavy." },
        modernVeh: { level: "moderate", label: "Diesel quality variable, altitude", detail: "Diesel is subsidized and cheap but quality/altitude can affect modern engines; Mercedes dealer presence is limited mainly to La Paz and Santa Cruz." },
        roadQuality: { level: "hard", label: "Rough, high-altitude routes", detail: "Many routes including famous ones like the Death Road and Altiplano tracks are unpaved, high-altitude, and prone to landslides/flooding in the wet season; 4x4 clearance is very useful." },
      },
    },
    { id: "BRA_north", iso: "BRA", name: "Brazil – North/Amazon", lat: -4, lng: -60, continent: "South America",
      climate: {
        codes: "VVVVOOOOOOOV",
        extra: ["HR", "HR", "HR", "R", "", "", "", "", "", "", "", "HR"],
        note: "Equatorial Amazon climate is hot and humid year-round; wettest Dec-May with river flooding, drier (relatively) Jun-Nov.",
      },
      complexity: {
        visa: { level: "easy", label: "Visa-free entry", detail: "Belgian/EU passport holders enter visa-free for tourism, currently up to 90 days (Brazil periodically reintroduces e-visa requirements for some nationalities, but EU citizens are typically exempt as of recent policy)." },
        particular: { level: "moderate", label: "Remote logistics, indigenous land", detail: "No mandatory guide, but large stretches are only accessible by river or unpaved road; some indigenous reserve areas (FUNAI) restrict entry and require permits." },
        stayLength: { level: "easy", label: "90 days typical", detail: "Tourist stays of up to 90 days are standard, extendable once." },
        extendStay: { level: "moderate", label: "Polícia Federal extension", detail: "One extension of up to 90 more days can be requested at a Polícia Federal office; routine but requires in-person visit and fee." },
        carnet: { level: "moderate", label: "Not required, TIP used", detail: "No Carnet de Passage required; a free Temporary Vehicle Import Permit (issued by Receita Federal) is standard at land borders." },
        vehicleStay: { level: "easy", label: "TIP matches visa, 90 days", detail: "Vehicle permit generally mirrors the 90-day tourist stay." },
        extendVeh: { level: "moderate", label: "Extend with Receita Federal", detail: "Extending the vehicle permit alongside a visa extension requires visiting Receita Federal; feasible but bureaucratic." },
        modernVeh: { level: "hard", label: "Sparse service in the Amazon", detail: "Diesel is available in river towns but quality/consistency drops in remote areas; Mercedes service is essentially absent outside Manaus." },
        roadQuality: { level: "hard", label: "Few roads, ferries essential", detail: "Much of the region has no road access at all — travel relies on river ferries/barges; existing roads like the Trans-Amazonian can be impassable mud during wet months." },
      },
    },
    { id: "BRA_northeast", iso: "BRA", name: "Brazil – Northeast", lat: -8, lng: -38, continent: "South America",
      climate: {
        codes: "OOOOOIIIIIOO",
        extra: ["H", "H", "", "", "", "", "", "", "T", "T", "", ""],
        note: "Hot year-round with a short rainy season (Mar-Jul on the coast); best conditions and popular Carnival season Sept-Nov coincide with dry, sunny weather and busier coastal towns.",
      },
      complexity: {
        visa: { level: "easy", label: "Visa-free entry", detail: "Same national policy: 90 days visa-free for Belgian/EU tourists." },
        particular: { level: "easy", label: "No special permits", detail: "No mandatory guide or special permits; standard tourist rules apply along the coast." },
        stayLength: { level: "easy", label: "90 days typical", detail: "Standard 90-day tourist stay, extendable once." },
        extendStay: { level: "moderate", label: "Polícia Federal extension", detail: "Extension handled at Polícia Federal offices in cities like Recife, Salvador or Fortaleza; routine process." },
        carnet: { level: "moderate", label: "Not required, TIP used", detail: "No Carnet de Passage needed; free Temporary Import Permit issued at the border by Receita Federal." },
        vehicleStay: { level: "easy", label: "TIP matches visa, 90 days", detail: "Vehicle permit typically matches the 90-day tourist stay." },
        extendVeh: { level: "moderate", label: "Extend with Receita Federal", detail: "Extension requires an in-person visit to Receita Federal; manageable with some Portuguese or patience." },
        modernVeh: { level: "easy", label: "Good coastal infrastructure", detail: "Coastal cities (Recife, Salvador, Fortaleza) have good diesel availability and Mercedes-Benz dealer/service coverage." },
        roadQuality: { level: "easy", label: "Good coastal highways", detail: "Coastal BR-101 and connecting roads are generally well paved; interior sertão roads are rougher but passable, with occasional flash flooding in the short rainy season." },
      },
    },
    { id: "BRA_south", iso: "BRA", name: "Brazil – South/Southeast", lat: -23, lng: -47, continent: "South America",
      climate: {
        codes: "OOOIIIOIIOOO",
        extra: ["H", "H", "", "", "C", "C", "", "", "T", "", "", "T"],
        note: "Subtropical climate with four seasons; mild and pleasant Apr-Jun and Sept-Nov, hot/humid summer (Dec-Feb) and occasional cold snaps in southern winter (Jun-Aug).",
      },
      complexity: {
        visa: { level: "easy", label: "Visa-free entry", detail: "90 days visa-free for Belgian/EU passport holders, same nationwide policy." },
        particular: { level: "easy", label: "No special permits", detail: "No mandatory guide or special permits; this is Brazil's most developed region for independent travel." },
        stayLength: { level: "easy", label: "90 days typical", detail: "Standard 90-day tourist stay, extendable once." },
        extendStay: { level: "easy", label: "Polícia Federal extension", detail: "Extensions are straightforward at Polícia Federal offices in São Paulo, Rio de Janeiro, or other major cities." },
        carnet: { level: "moderate", label: "Not required, TIP used", detail: "No Carnet de Passage required; free Temporary Import Permit issued at the border by Receita Federal." },
        vehicleStay: { level: "easy", label: "TIP matches visa, 90 days", detail: "Vehicle import permit typically matches the 90-day tourist stay." },
        extendVeh: { level: "easy", label: "Extend with Receita Federal", detail: "Extension process is well-established in this region given the density of Receita Federal offices." },
        modernVeh: { level: "easy", label: "Excellent service network", detail: "São Paulo and Rio have full Mercedes-Benz dealer networks, diesel of good quality is universally available, and parts/service for a Sprinter are easy to find." },
        roadQuality: { level: "easy", label: "Good highways, some tolls", detail: "Well-maintained toll highways connect major cities; mountain roads (Serra do Mar) can be foggy/slippery in wet season but are well engineered." },
      },
    },
    { id: "CHL", iso: "CHL", name: "Chile", lat: -36.6, lng: -71.3, continent: "South America",
      climate: {
        codes: "IIOVVVVVVOII",
        extra: ["T", "T", "", "C", "C", "C", "C", "C", "C", "", "", "T"],
        note: "Long north-south stretch: desert north is warm year-round, central zone mild with dry summers, Patagonian south best Nov-Mar with severe winter cold/closures Jun-Aug.",
      },
      complexity: {
        visa: { level: "easy", label: "Visa-free entry", detail: "Belgian/EU passport holders enter visa-free for tourism, up to 90 days." },
        particular: { level: "moderate", label: "Agricultural checks strict", detail: "No mandatory guide, but SAG agricultural inspections at internal and external borders are strict (fresh food, fruit, seeds are commonly confiscated)." },
        stayLength: { level: "easy", label: "90 days typical", detail: "Standard tourist stay is 90 days, stamped on entry." },
        extendStay: { level: "moderate", label: "Extension via PDI/Migraciones", detail: "One extension is possible via the Policía de Investigaciones (PDI) or by a border run, e.g. into Argentina and back." },
        carnet: { level: "moderate", label: "Not required but useful", detail: "Chile does not strictly require a Carnet de Passage; a free Temporary Import document is issued at the border, but many travelers carry a carnet for smoother handling at the frequent Chile-Argentina crossings." },
        vehicleStay: { level: "easy", label: "TIP matches visa, 90 days", detail: "Vehicle import permit is generally issued for 90 days alongside the personal visa." },
        extendVeh: { level: "moderate", label: "Extend with Aduana", detail: "Extension requires visiting a Servicio Nacional de Aduanas office; feasible but requires planning ahead of expiry." },
        modernVeh: { level: "easy", label: "Excellent service network", detail: "Chile has some of South America's best diesel quality and infrastructure, with a solid Mercedes-Benz dealer network in Santiago and regional cities." },
        roadQuality: { level: "easy", label: "Well maintained overall", detail: "The Panamericana (Ruta 5) runs the length of the country and is excellent; Patagonian side roads can be gravel and affected by wind, and southern passes close with winter snow." },
      },
    },
    { id: "COL", iso: "COL", name: "Colombia", lat: 4.07, lng: -72.93, continent: "South America",
      climate: {
        codes: "OOOVVOOOOVVO",
        extra: ["", "", "", "R", "R", "", "", "", "", "R", "R", ""],
        note: "Tropical, altitude-dependent climate with two rainy seasons (Apr-May and Oct-Nov); driest and best conditions Dec-Mar and Jul-Aug.",
      },
      complexity: {
        visa: { level: "easy", label: "Visa-free entry", detail: "Belgian/EU passport holders enter visa-free for up to 90 days, extendable to 180 days per year." },
        particular: { level: "moderate", label: "Darién Gap has no road", detail: "No mandatory guide requirement, but the Darién Gap to/from Panama has no road connection at all — vehicles must be shipped by roll-on/roll-off ferry or container from Cartagena/Colón." },
        stayLength: { level: "easy", label: "90 days, extendable", detail: "Initial stay of 90 days can be extended once for a combined maximum of 180 days per calendar year." },
        extendStay: { level: "easy", label: "Online Migración extension", detail: "Extension can be done online via the Migración Colombia portal or in person; a relatively easy and well-documented process." },
        carnet: { level: "moderate", label: "No land border, ship required", detail: "No Carnet de Passage required for entry by sea; since there's no road link with Panama, the vehicle must be shipped (RoRo or container), which involves its own customs paperwork on both ends." },
        vehicleStay: { level: "easy", label: "TIP typically 90 days", detail: "Temporary Import Permit for the vehicle is generally issued for up to 90 days, extendable to match the visa extension." },
        extendVeh: { level: "moderate", label: "Extend with DIAN", detail: "Vehicle permit extension is handled through DIAN (customs authority); doable in step with the personal visa extension." },
        modernVeh: { level: "moderate", label: "Good in cities, variable elsewhere", detail: "Bogotá and Medellín have Mercedes-Benz dealer presence and decent diesel quality; more remote areas have less consistent fuel quality and no dealer support." },
        roadQuality: { level: "moderate", label: "Good highways, mountain risk", detail: "Major intercity highways are reasonably good, though mountainous terrain brings landslide risk in rainy season and some routes have had historical security concerns (improving steadily)." },
      },
    },
    { id: "ECU", iso: "ECU", name: "Ecuador", lat: -1.79, lng: -78.1, continent: "South America",
      climate: {
        codes: "OOOOOIIIIIOO",
        extra: ["", "R", "R", "", "", "", "", "", "", "", "", ""],
        note: "Andean highlands are mild year-round; coast has a wet season Dec-May and dry season Jun-Nov which is generally the best travel window.",
      },
      complexity: {
        visa: { level: "easy", label: "Visa-free entry", detail: "Belgian/EU passport holders enter visa-free for up to 90 days per year as tourists." },
        particular: { level: "easy", label: "No special permits", detail: "No mandatory guide requirements for mainland travel (Galápagos has separate rules for cruises/land tours but is not relevant for the mainland vehicle route)." },
        stayLength: { level: "easy", label: "90 days per year", detail: "Standard entry grants up to 90 cumulative days per calendar year." },
        extendStay: { level: "moderate", label: "Limited extension options", detail: "Extensions beyond 90 days are limited for tourist status; most overlanders simply plan to exit before the limit or apply for a different visa category." },
        carnet: { level: "moderate", label: "Not required, TIP used", detail: "No Carnet de Passage required; a free Temporary Vehicle Import Permit is issued at the border by Ecuadorian customs (SENAE)." },
        vehicleStay: { level: "easy", label: "TIP matches visa, 90 days", detail: "Vehicle permit typically matches the 90-day personal stay allowance." },
        extendVeh: { level: "moderate", label: "Extension tied to visa limits", detail: "Extending the vehicle permit follows the same constraints as personal stay extension — generally not flexible beyond the 90-day annual allowance." },
        modernVeh: { level: "moderate", label: "Decent in cities, altitude effects", detail: "Quito and Guayaquil have Mercedes-Benz dealer presence; high-altitude driving (Andes over 3000m) affects diesel engine performance somewhat but modern turbo-diesels handle it well." },
        roadQuality: { level: "moderate", label: "Good highways, landslide risk", detail: "Main highways are well paved, but mountainous sections are prone to landslides in the wet season, and coastal roads can flood during heavy rains." },
      },
    },
    { id: "GUF", iso: "GUF", name: "French Guiana", lat: 3.9, lng: -53.09, continent: "South America",
      climate: {
        codes: "OOOVVOOOOOOO",
        extra: ["R", "R", "R", "R", "R", "", "", "", "", "", "", ""],
        note: "Equatorial climate, hot and humid year-round; long rainy season Dec-Jul (heaviest Apr-May), best travel conditions during the drier Aug-Nov period.",
      },
      complexity: {
        visa: { level: "easy", label: "No visa, EU external territory", detail: "French Guiana is an overseas department of France (EU outermost region); Belgian/EU citizens enter with just an ID card or passport, no visa or immigration formalities, as if visiting France itself." },
        particular: { level: "moderate", label: "Not Schengen, French customs rules", detail: "Despite being an EU territory and using the euro, French Guiana is outside the Schengen Area and outside the EU customs union for goods — so unlike driving within Schengen Europe, your vehicle still undergoes formal French customs (douane) formalities on arrival, typically via the ferry/barge route from Suriname (Albina–Saint-Laurent-du-Maroni) or the Oiapoque bridge from Brazil." },
        stayLength: { level: "easy", label: "No limit for EU citizens", detail: "As EU citizens, Belgians can stay indefinitely as in mainland France; no tourist stay limit applies." },
        extendStay: { level: "easy", label: "Not applicable", detail: "No extension needed given unrestricted EU freedom of movement rights in this French territory." },
        carnet: { level: "moderate", label: "French customs TIP, no carnet", detail: "No Carnet de Passage is required for EU-registered vehicles; French customs issue standard temporary admission documentation, but non-EU-plated vehicles (and even EU-plated ones arriving from Suriname/Brazil rather than mainland France) should expect a formal customs declaration at the border post." },
        vehicleStay: { level: "easy", label: "Unrestricted for EU-plated vans", detail: "A Belgian-plated vehicle can generally remain as long as the traveler does, consistent with EU intra-territory rules, though it entered via a non-EU land border so keep import paperwork from that crossing." },
        extendVeh: { level: "easy", label: "Not applicable", detail: "No formal extension process needed under EU vehicle movement rules." },
        modernVeh: { level: "moderate", label: "French-standard fuel, small network", detail: "Diesel quality matches French/EU standards; however there is no Mercedes-Benz dealer in French Guiana itself — nearest full service is via France (shipped parts) or across the border in Brazil/Suriname." },
        roadQuality: { level: "moderate", label: "Limited road network, rainforest", detail: "The paved road network is limited to a narrow coastal corridor (Saint-Laurent-du-Maroni to Saint-Georges); heavy rains Dec-Jul can cause flooding, and much of the interior has no road access at all." },
      },
    },
    { id: "GUY", iso: "GUY", name: "Guyana", lat: 4.82, lng: -58.97, continent: "South America",
      climate: {
        codes: "OOOVVOOOOVVO",
        extra: ["R", "R", "", "R", "R", "", "", "", "", "R", "R", ""],
        note: "Tropical climate with two rainy seasons (Apr-Aug main, Nov-Jan shorter); driest and best travel windows are roughly Sept-Oct and Feb-Mar.",
      },
      complexity: {
        visa: { level: "easy", label: "Visa-free entry", detail: "Belgian/EU passport holders enter visa-free for tourism, typically granted up to 30-90 days at immigration officer discretion." },
        particular: { level: "moderate", label: "Limited road border options", detail: "No mandatory guide, but land border crossings are limited (Lethem from Brazil, Moleson Creek/ferry from Suriname); interior travel largely relies on unpaved roads or river/air access." },
        stayLength: { level: "moderate", label: "Up to 90 days, officer discretion", detail: "Stay length is decided at entry, commonly 30 days but can be extended to 90 by the immigration officer or on request." },
        extendStay: { level: "moderate", label: "Immigration office extension", detail: "Extensions are handled at the Ministry of Home Affairs immigration office in Georgetown; process works but requires an in-person visit." },
        carnet: { level: "moderate", label: "Not required, TIP used", detail: "No Carnet de Passage required; Guyana Revenue Authority issues a Temporary Import Permit for foreign vehicles at the border." },
        vehicleStay: { level: "moderate", label: "Typically 30-90 days", detail: "Vehicle TIP duration generally mirrors the personal stay permit granted at entry." },
        extendVeh: { level: "moderate", label: "Extend via GRA customs", detail: "Extending the vehicle permit requires contacting the Guyana Revenue Authority; manageable but requires some legwork in Georgetown." },
        modernVeh: { level: "hard", label: "Very limited service network", detail: "No Mercedes-Benz dealer presence in the country; diesel is available in Georgetown and along main roads but quality and availability drop off quickly in the interior." },
        roadQuality: { level: "hard", label: "Mostly unpaved outside capital", detail: "Roads outside Georgetown are largely unpaved laterite, becoming very difficult or impassable in the rainy season; the Lethem-Georgetown road has seen recent paving progress but sections remain rough." },
      },
    },
    { id: "PRY", iso: "PRY", name: "Paraguay", lat: -23.45, lng: -58.49, continent: "South America",
      climate: {
        codes: "VVOOIIIIOOOV",
        extra: ["H", "H", "", "", "", "C", "C", "", "", "", "", "H"],
        note: "Subtropical climate with hot, humid summers (Dec-Feb) and mild, dry winters (Jun-Aug) which are the most comfortable months for travel.",
      },
      complexity: {
        visa: { level: "easy", label: "Visa-free entry", detail: "Belgian/EU passport holders enter visa-free for tourism, typically up to 90 days." },
        particular: { level: "easy", label: "No special permits", detail: "No mandatory guide or special permit requirements for standard overland travel." },
        stayLength: { level: "easy", label: "90 days typical", detail: "Standard tourist stay of 90 days is granted on arrival." },
        extendStay: { level: "moderate", label: "Migraciones extension", detail: "Extensions are handled at the Dirección General de Migraciones in Asunción; a workable but bureaucratic process." },
        carnet: { level: "moderate", label: "Not required, TIP used", detail: "No Carnet de Passage required; a free Temporary Import Permit is issued at the border by Paraguayan customs." },
        vehicleStay: { level: "easy", label: "TIP matches visa, 90 days", detail: "Vehicle permit typically mirrors the 90-day personal tourist stay." },
        extendVeh: { level: "moderate", label: "Extend with Aduana", detail: "Extending the vehicle permit requires an in-person visit to a customs (Aduana) office; routine but needs planning." },
        modernVeh: { level: "moderate", label: "Decent in Asunción, sparse rurally", detail: "Diesel is widely available; Mercedes-Benz has a dealer presence in Asunción but service options thin out quickly in rural areas." },
        roadQuality: { level: "moderate", label: "Good main routes, rough rural", detail: "The main Ruta 1/2/7 corridors are paved and reasonably maintained; rural and Chaco roads are unpaved and can become very difficult after heavy rain." },
      },
    },
    { id: "PER", iso: "PER", name: "Peru", lat: -9.2, lng: -75.04, continent: "South America",
      climate: {
        codes: "OOOIIIVVIIOO",
        extra: ["R", "R", "R", "", "", "", "TC", "TC", "T", "", "", ""],
        note: "Coast is mild/dry year-round; Andean highlands (incl. Cusco/Machu Picchu) have a dry season May-Sep that is ideal for trekking but very crowded with tourists and cold at altitude, wet Dec-Mar.",
      },
      complexity: {
        visa: { level: "easy", label: "Visa-free entry", detail: "Belgian/EU passport holders enter visa-free for tourism, typically granted up to 90 or 180 days at the immigration officer's discretion (183 days per year cumulative)." },
        particular: { level: "moderate", label: "Machu Picchu permit system", detail: "No mandatory guide for general overland travel, but visiting Machu Picchu requires a timed-entry ticket purchased in advance, and some Inca Trail sections require a licensed guide by law." },
        stayLength: { level: "easy", label: "Up to 183 days typical", detail: "Entry stamp commonly grants 90-183 days depending on the immigration officer; check the stamped date carefully." },
        extendStay: { level: "moderate", label: "Migraciones extension", detail: "Extensions can be requested at a Superintendencia Nacional de Migraciones office; process is manageable but requires paperwork." },
        carnet: { level: "moderate", label: "Not required, TIP used", detail: "No Carnet de Passage required; Peruvian customs (SUNAT) issues a free Temporary Import Permit for foreign vehicles at the border, typically for the same duration as the visa." },
        vehicleStay: { level: "easy", label: "Matches visa, up to 183 days", detail: "Vehicle TIP is generally issued matching the personal stay period granted at entry." },
        extendVeh: { level: "moderate", label: "Extend with SUNAT", detail: "Vehicle permit extensions are handled by SUNAT customs; process works but requires an in-person visit and can take time." },
        modernVeh: { level: "moderate", label: "Good in Lima, variable elsewhere", detail: "Lima has a full Mercedes-Benz dealer network and good diesel quality; more remote highland and jungle areas have less consistent fuel quality and no dealer support." },
        roadQuality: { level: "moderate", label: "Good Panamericana, rough Andes", detail: "The coastal Panamericana highway is excellent; Andean mountain roads are spectacular but narrow, prone to landslides in wet season (Dec-Mar), and high passes can be affected by snow/ice." },
      },
    },
    { id: "SUR", iso: "SUR", name: "Suriname", lat: 3.92, lng: -56.0, continent: "South America",
      climate: {
        codes: "OOOVVOOOOVVO",
        extra: ["R", "R", "", "R", "R", "", "", "", "", "R", "R", ""],
        note: "Tropical climate with two rainy seasons (Apr-Aug main, late Nov-Jan minor); driest and most pleasant conditions are roughly Feb-Mar and Aug-Nov.",
      },
      complexity: {
        visa: { level: "easy", label: "e-Visa or visa-free varies", detail: "Belgian/EU passport holders can typically obtain a tourist card/e-visa online in advance or occasionally on arrival; check current requirements as Suriname's system has changed in recent years." },
        particular: { level: "moderate", label: "Limited road network", detail: "No mandatory guide, but the road network is limited mostly to the coastal strip; the interior is largely accessible only by river or air." },
        stayLength: { level: "moderate", label: "Typically 90 days", detail: "Tourist cards/e-visas are usually valid for stays of up to 90 days." },
        extendStay: { level: "moderate", label: "Immigration office extension", detail: "Extensions are handled through the Immigration Department in Paramaribo; process is workable but requires an in-person visit." },
        carnet: { level: "moderate", label: "Not required, TIP used", detail: "No Carnet de Passage required; Surinamese customs issues a temporary import document for foreign vehicles at the border, including at the Albina ferry crossing from French Guiana." },
        vehicleStay: { level: "moderate", label: "Typically 90 days", detail: "Vehicle import permit generally mirrors the personal tourist stay period." },
        extendVeh: { level: "moderate", label: "Extend via customs office", detail: "Extending the vehicle permit requires contacting Surinamese customs in Paramaribo; manageable with some planning." },
        modernVeh: { level: "hard", label: "Very limited service network", detail: "No Mercedes-Benz dealer presence; diesel is available along the coastal corridor but quality and reliability of supply and service drop sharply in the interior." },
        roadQuality: { level: "hard", label: "Coastal roads ok, interior poor", detail: "The coastal east-west corridor is reasonably paved; roads south into the interior are unpaved, limited, and often impassable in the rainy season." },
      },
    },
    { id: "URY", iso: "URY", name: "Uruguay", lat: -32.53, lng: -55.82, continent: "South America",
      climate: {
        codes: "OOOIIOOIIOOO",
        extra: ["H", "H", "", "", "", "", "", "", "", "", "", ""],
        note: "Temperate climate with warm summers (Dec-Feb) and mild winters; spring (Sept-Nov) and autumn (Mar-May) offer the most comfortable travel conditions.",
      },
      complexity: {
        visa: { level: "easy", label: "Visa-free entry", detail: "Belgian/EU passport holders enter visa-free for tourism, typically up to 90 days, extendable." },
        particular: { level: "easy", label: "No special permits", detail: "No mandatory guide or special permit requirements; one of the most straightforward countries in the region for independent travel." },
        stayLength: { level: "easy", label: "90 days, extendable", detail: "Standard tourist stay of 90 days, extendable for another 90 days." },
        extendStay: { level: "easy", label: "Simple Migración extension", detail: "Extension is a simple, well-organized process at Dirección Nacional de Migración offices, including in Montevideo." },
        carnet: { level: "moderate", label: "Not required, TIP used", detail: "No Carnet de Passage required; a free Temporary Import Permit is issued at the border by Uruguayan customs (DNA)." },
        vehicleStay: { level: "easy", label: "TIP matches visa, 90 days", detail: "Vehicle permit typically mirrors the 90-day personal tourist stay, extendable alongside it." },
        extendVeh: { level: "easy", label: "Straightforward extension", detail: "Vehicle permit extension is a relatively simple process handled together with the personal stay extension." },
        modernVeh: { level: "easy", label: "Excellent service network", detail: "Uruguay has good diesel quality and a Mercedes-Benz dealer presence in Montevideo; one of the easier countries in South America for vehicle support." },
        roadQuality: { level: "easy", label: "Well maintained nationwide", detail: "Roads are generally well paved and maintained across this small, flat country, with minimal seasonal hazards." },
      },
    },
    { id: "VEN", iso: "VEN", name: "Venezuela", lat: 6.44, lng: -66.53, continent: "South America",
      climate: {
        codes: "OOOVVVVOOOVV",
        extra: ["", "", "", "R", "R", "R", "R", "", "", "", "R", "R"],
        note: "Tropical climate, hot year-round with a wet season roughly May-Nov (heaviest Jun-Aug); dry season Dec-Apr is more favorable, though political/security conditions are a much bigger constraint than climate.",
      },
      complexity: {
        visa: { level: "hard", label: "Visa-free but high risk travel", detail: "Belgian/EU passport holders technically enter visa-free for tourism, but current government travel advisories from Belgium/EU foreign ministries strongly warn against travel due to security, crime, and political instability; situation is fluid and should be checked immediately before any trip." },
        particular: { level: "hard", label: "Severe security concerns", detail: "No formal guide requirement, but extremely high crime rates, risk of extortion at checkpoints, fuel shortages, and cash/currency instability make independent overlanding very high-risk in practice; many overland routes through South America currently bypass Venezuela entirely." },
        stayLength: { level: "moderate", label: "90 days typical", detail: "Where entry is possible, tourist stays of up to 90 days are nominally granted." },
        extendStay: { level: "hard", label: "Bureaucratic and unreliable", detail: "Extensions through SAIME (immigration authority) are reported as slow, inconsistent, and subject to sudden policy changes." },
        carnet: { level: "hard", label: "Uncertain, poorly documented", detail: "Carnet de Passage requirements and enforcement are inconsistently documented and enforcement varies by crossing; land border crossings from Colombia/Brazil are also subject to closures amid political tensions." },
        vehicleStay: { level: "hard", label: "Unclear, situation fluid", detail: "Vehicle import duration rules exist on paper but practical application is unreliable given current institutional instability." },
        extendVeh: { level: "hard", label: "Very difficult in practice", detail: "Extending any vehicle permit requires navigating an unpredictable bureaucracy amid fuel and cash shortages." },
        modernVeh: { level: "hard", label: "Severe fuel/parts shortages", detail: "Despite vast oil reserves, Venezuela suffers chronic fuel shortages and long queues; no reliable Mercedes-Benz dealer support remains functional at a normal level; spare parts are very difficult to source." },
        roadQuality: { level: "hard", label: "Deteriorating, security risk", detail: "Road infrastructure has deteriorated significantly due to lack of maintenance investment; some routes carry real crime/kidnapping risk in addition to physical road hazards." },
      },
    },
  ];
  window.COUNTRY_DATA = window.COUNTRY_DATA || [];
  window.COUNTRY_DATA.push(...SOUTH_AMERICA_COUNTRIES);
})();
